/* ===========================================================================
   Project case-study data (content only). Pure data — no rendering logic.
   The page is src/pages/projects/[slug].astro; JSON-LD lives in ./schema.mjs.
   =========================================================================== */

export { SITE } from "../site.mjs";

export const projects = [
  {
    slug: "redline",
    // Design copy for the Portfolio + Case Study templates (brandbook redesign).
    sector: "E-commerce", tags: "Brand · E-commerce", location: "India",
    stack: "Next.js · Razorpay", scope: "Brand identity, storefront, payments",
    line: "A motorcycle-apparel brand born out of speed — F1-styled motion, race-car geometry and a colour system pulled from real racing liveries.",
    brief: "A motorcycle apparel brand built around speed needed an identity, a storefront and payments — as one piece of work, in a single sprint.",
    build: ["F1-track-styled loaders and race-car geometry","Hand-picked racing colour system","Razorpay with UPI, card and cash on delivery","No platform fees, no theme licences"],
    stats: [["1","Sprint, brand to checkout"],["3","Ways to pay: UPI, card, COD"],["0","Platform fees"]],
    quote: null,
    num: "01", name: "Redline Studios", category: "Brand · E-commerce", year: "2025",
    liveUrl: "https://redlinestudios.in",
    domain: "redlinestudios.in",
    headlineTail: "— apparel storefront",
    updated: "2026-07-28",
    stackLine: "Next.js · Razorpay · Custom storefront",
    title: "Redline Studios — Apparel Storefront · Divyansh Sood",
    description: "A motorcycle apparel brand born out of speed. F1 track-styled loaders, race-car geometry, hand-picked colours. Custom Next.js + Razorpay — nothing templated.",
    ogTitle: "Redline Studios — apparel storefront · Case study",
    ogDescription: "Motorcycle apparel brand born out of speed — F1-styled storefront, hand-built.",
    ogImage: "https://www.divyanshsood.com/images/work/redline-1.webp",
    keywords: "motorcycle apparel storefront, custom e-commerce India, Next.js storefront, Razorpay store, brand identity, F1 styled website, no Shopify, Divyansh Sood",
    feature: { src: "/images/work/redline-1.webp", alt: "Redline Studios — SS26 lookbook hero on desktop" },
    body: [
      { tag: "The brief", title: "A storefront that feels like a track", type: "prose",
        html: `Not a Shopify theme dressed up in red and black. Something where every easing curve, loading state and product reveal carries the brand's <em>racing DNA</em>.` },
      { tag: "Founder, in 3 words", type: "quote",
        quote: `"Bhai bhai bhai! Ye kya banal cheez bana dia."`,
        // Gloss keeps the warmth of the original Hindi/Hinglish line for
        // Indian readers, while the English underneath makes the line
        // land for a US/UK prospect who doesn't read Devanagari.
        gloss: `"Bro bro bro! What a thing you've built."`,
        lang: "hi",
        attribution: "— Founder, Redline Studios" },
      { tag: "Stack", type: "list", items: ["Next.js", "Razorpay", "Custom motion", "Brand identity"] },
      { tag: "What we shipped", title: "Brand + backend + frontend, one sprint", type: "prose",
        html: `A custom Next.js storefront with <strong>Razorpay</strong> (UPI, cards, COD), <strong>F1-inspired motion</strong> language, and a colour system pulled from actual racing liveries. Backend, frontend, design — one sprint.` },
      { tag: "The result", title: "A brand that launched selling, not waiting", type: "prose",
        html: `Redline went from no identity and no storefront to <strong>live and taking payments in a single sprint</strong> — the logo, the motion language and the checkout all arriving together instead of a brand book sitting idle while a store gets built. Because it is custom code rather than a theme, there is no monthly platform fee and no licence to renew, and the next change to the buy flow does not need anyone's permission.` },
      { tag: "The lesson", type: "prose",
        html: `When the brand and the storefront are made by the same person at the same time, the brand survives contact with the checkout. Split them and the identity gets flattened into whatever the theme allows.` },
    ],
    gallery: [
      { src: "/images/work/redline-1.webp", alt: "Redline Studios — SS26 lookbook hero" },
    ],
    faq: [
      { q: "What is Redline Studios?", a: "Redline Studios is a motorcycle-apparel brand whose identity and storefront were built end-to-end by Divyansh Sood Studio — F1-styled motion, race-car geometry and a colour system pulled from real racing liveries." },
      { q: "Was the store built on Shopify?", a: "No. It is a custom Next.js storefront with zero Shopify themes, integrated with Razorpay for UPI, cards and cash on delivery." },
      { q: "How long did it take?", a: "Brand identity, backend, frontend and design were all delivered in a single sprint." },
    ],
  },
  {
    slug: "cultxberserk",
    // Design copy for the Portfolio + Case Study templates (brandbook redesign).
    sector: "E-commerce", tags: "Brand · D2C", location: "India",
    stack: "Next.js · ImageKit", scope: "Storefront, drop system, lore surfaces",
    line: "A Berserk-inspired apparel label where the lore and the buy flow are one experience — with a hand-numbered drop system enforced in code.",
    brief: "Heavyweight tees hand-numbered 0001 to 0666, thirteen designs, never reprinted. A Shopify theme structurally cannot express that scarcity.",
    build: ["Hand-numbered drop system enforced by the storefront","Three lore surfaces built alongside the buy flow","Next.js with ImageKit media pipeline","Designs retire permanently once sold"],
    stats: [["0666","Units per design, max"],["13","Designs, never reprinted"],["3","Lore surfaces"]],
    quote: null,
    num: "02", name: "CultXberserk", category: "Brand · D2C", year: "2026",
    liveUrl: "https://cultxberserk.com",
    domain: "cultxberserk.com",
    headlineTail: "— Berserk-inspired apparel",
    updated: "2026-07-28",
    stackLine: "Next.js · ImageKit · Custom storefront",
    title: "CultXberserk — Anime Apparel Brand Store · Divyansh Sood",
    description: "A gothic apparel label built around the world of Berserk. Hand-numbered drops (0001–0666), 13 designs never reprinted. Custom-coded — no Shopify theme.",
    ogTitle: "CultXberserk — Berserk-inspired apparel · Case study",
    ogDescription: "A lore-driven apparel brand with hand-numbered drops and a custom-coded storefront. No Shopify theme.",
    ogImage: "https://www.divyanshsood.com/images/work/cultxberserk-1.webp",
    keywords: "Berserk apparel, gothic streetwear brand, hand-numbered drops, custom e-commerce India, Next.js storefront, anime apparel, D2C clothing brand, no Shopify, Divyansh Sood",
    feature: { src: "/images/work/cultxberserk-1.webp", alt: "CultXberserk — lore-driven storefront hero on desktop" },
    body: [
      { tag: "The bet", title: "Lore-driven commerce, not a merch store", type: "prose",
        html: `Most anime-adjacent labels print a graphic and ship it on a generic store. CultXberserk is the opposite: a brand with its own canon — Japanese lettering, Roman numerals, a <em>"Brand of Sacrifice"</em> seal at the C7 vertebra — where the storytelling and the storefront are built as one thing.` },
      { tag: "Brand voice", type: "quote",
        quote: `"Apparel for the damned."` },
      { tag: "Stack", type: "list", items: ["Next.js", "ImageKit", "Custom cart", "Drop mechanics"] },
      { tag: "What we shipped", title: "A storefront that reads like the manga", type: "prose",
        html: `A custom Next.js storefront with <strong>ImageKit</strong>-optimised product imagery, a <strong>hand-numbered drop system</strong> (0001–0666, never reprinted), and dedicated <em>Lore</em>, <em>Drops</em> and <em>Council</em> surfaces so the world-building lives next to the buy button. Zero Shopify themes — full code ownership, end to end.` },
      { tag: "The result", title: "Scarcity the system enforces, not the founder", type: "prose",
        html: `The drop mechanic is <strong>part of the software</strong>: numbers are issued in sequence, a design retires when its run is done, and nothing has to be manually pulled or tracked in a sheet. That matters for a brand whose entire promise is that a piece is never reprinted — the claim is only as good as the thing enforcing it. No app store sells this mechanic, which is the reason it is coded rather than configured.` },
      { tag: "The lesson", type: "prose",
        html: `If your brand's promise is a mechanic, the mechanic has to live in the product. Anything a founder has to remember to do by hand is a promise waiting to break on a busy launch day.` },
    ],
    gallery: [
      { src: "/images/work/cultxberserk-1.webp", alt: "CultXberserk — lore-driven storefront hero" },
      { src: "/images/work/cultxberserk-2.webp", alt: "CultXberserk — brand lore section" },
    ],
    faq: [
      { q: "What is CultXberserk?", a: "CultXberserk is a gothic apparel brand inspired by Kentaro Miura's manga Berserk, with a custom-coded storefront built by Divyansh Sood Studio. It sells heavyweight, garment-dyed tees that are hand-numbered and never reprinted." },
      { q: "Was the store built on Shopify?", a: "No. It is a custom Next.js storefront with ImageKit-optimised imagery and a bespoke drop system — zero Shopify themes, so the brand keeps full code ownership." },
      { q: "What makes the drops exclusive?", a: "Every garment is hand-numbered from 0001 to 0666 across 13 designs and is never reprinted, and each carries a 'Brand of Sacrifice' seal sewn into the neckline at the C7 vertebra." },
    ],
  },
  {
    slug: "modernkbs",
    // Design copy for the Portfolio + Case Study templates (brandbook redesign).
    sector: "Web app", tags: "Web App · Admin", location: "Ladwara, Himachal Pradesh",
    stack: "Next.js · Supabase", scope: "School website, admissions portal, admin panel",
    line: "A school website plus admissions portal and a self-serve admin — delivered in 7 days, against a six-month agency quote.",
    brief: "A senior secondary school needed a public website and an admissions application portal, without a recurring SaaS subscription.",
    build: ["Public website and admissions portal in one sprint","Live admin panel threaded through every surface","Applications for classes I to XII managed by staff","No developer on call, no SaaS fees"],
    stats: [["7","Days to deliver"],["6","Months, other agencies' quote"],["I–XII","Classes handled"]],
    quote: ["Every other agency said 6 months. Delivered in 7 days.","Admin, Modern K.B.S."],
    num: "05", name: "Modern K.B.S.", category: "Web App · Admin", year: "2024",
    liveUrl: "https://modernkbs.com",
    domain: "modernkbs.com",
    headlineTail: "— school site + admin panel",
    updated: "2026-09-29",
    stackLine: "Next.js · Supabase · Admin dashboard",
    service: { href: "/services/travel-website-development/", label: "Travel & taxi website development" },
    service: { href: "/services/school-website-development/", label: "School website development" },
    title: "Modern K.B.S. — School Site + Admin Panel · Divyansh Sood",
    description: "A senior secondary school in Ladwara. Website + application portal shipped together with a live admin panel. Quoted at 6 months elsewhere — delivered in 7 days.",
    ogTitle: "Modern K.B.S. — school portal · Case study",
    ogDescription: "School site + admissions admin panel — 6 months elsewhere, 7 days here.",
    ogImage: "https://www.divyanshsood.com/images/work/modernkbs-1.webp",
    keywords: "school website India, admissions portal, school admin panel, Next.js Supabase, education website developer, fast website delivery, Divyansh Sood",
    feature: { src: "/images/work/modernkbs-1.webp", alt: "Modern K.B.S. — homepage hero on desktop" },
    body: [
      { tag: "The brief", title: "Admissions before the academic cycle", type: "prose",
        html: `The school had been quoted six months and a recurring SaaS fee for an admissions portal. They needed it before the next cycle — measured in <em>weeks</em>, not quarters. And the office staff (not developers) had to run it.` },
      { tag: "In their words", type: "quote",
        quote: `"Every other agency said 6 months. Delivered in 7 days."`,
        attribution: "— Admin, Modern K.B.S., Ladwara" },
      { tag: "Stack", type: "list", items: ["Next.js", "Supabase", "Custom admin", "Razorpay (fees)"] },
      { tag: "What we shipped", title: "Public site + admin panel, one sprint", type: "prose",
        html: `Faculty pages, fee structure, an enquiry-to-admission pipeline, and a <strong>dashboard the office uses daily</strong>. Zero learning curve — designed so any office staffer can update content without calling a developer.` },
      { tag: "The result", title: "Live for the admissions cycle it was built for", type: "prose",
        html: `Seven days from brief to a working admissions portal, against <strong>six months quoted elsewhere</strong> — which mattered because the deadline was not a preference, it was the academic calendar. A six-month build would have missed the intake entirely and the school would have run another year on paper forms. Classes I–XII now apply through the site, the office processes them in the dashboard, and there is <strong>no recurring SaaS fee</strong> attached to any of it.` },
      { tag: "Why six months", title: "Where the other quotes came from", type: "prose",
        html: `Six months isn't fraud. It's what happens when a project passes through discovery, wireframes, design review, development, staging, feedback rounds and QA, each with its own people and approvals. Here one person took it from brief to deployment. Just as important, only what the school needed was built: no general-purpose CMS, no theme with 300 settings, no features added “just in case”. That's how a site stays lightweight and fully functional at once.` },
      { tag: "The lesson", type: "prose",
        html: `Ask what the deadline is attached to. "Six months" is a reasonable estimate for a portal and a completely unreasonable one for a portal that has to exist before an intake — and scope, not speed, is what closes that gap.` },
    ],
    gallery: [
      { src: "/images/work/modernkbs-1.webp", alt: "Modern K.B.S. — homepage hero" },
      { src: "/images/work/modernkbs-2.webp", alt: "Modern K.B.S. — notices and toppers" },
    ],
    faq: [
      { q: "What is Modern K.B.S.?", a: "Modern K.B.S. is a senior secondary school in Ladwara. Divyansh Sood Studio built its public website plus an admissions application portal and a live admin panel, all in one sprint." },
      { q: "How long did the build take?", a: "Seven days — where other agencies had quoted six months and a recurring SaaS fee." },
      { q: "Who runs the admin panel?", a: "Office staff, not developers. The dashboard was designed with zero learning curve so any staffer can update content and process admissions without calling a developer." },
      { q: "Why did other agencies quote six months for a school website?", a: "A multi-person agency process of discovery, wireframes, design review, development, staging, feedback and QA adds weeks at every handoff. Building with one person from brief to deployment, and only building what the school actually needed, is what made a 7-day delivery possible without cutting corners." },
    ],
  },
  {
    slug: "chinkiz",
    // Design copy for the Portfolio + Case Study templates (brandbook redesign).
    sector: "E-commerce", tags: "D2C · Creator", location: "India",
    stack: "Next.js · Razorpay", scope: "Creator storefront, video gallery, admin",
    line: "Shopify and Webflow fought the way her audience shops. A custom-coded storefront puts the video right next to the buy button.",
    brief: "A creator with 600K+ YouTube subscribers needed to sell handmade products directly. Two previous builders had failed.",
    build: ["Native video gallery matching the ritual of her tutorials","Razorpay payments","Self-serve admin — add a product like uploading a video","No Shopify, no theme marketplace"],
    stats: [["600K+","Subscriber audience"],["2","Weeks to live"],["2","Failed builds before"]],
    quote: ["I did not think it could be achieved without going to e-commerce builders and only using custom code.","Chinki, Founder"],
    num: "03", name: "ChinkiZ Knitting Knife", category: "D2C · Creator", year: "2024",
    liveUrl: "https://chinkizknittingknife.com",
    domain: "chinkizknittingknife.com",
    headlineTail: "— D2C storefront",
    updated: "2026-09-29",
    stackLine: "Next.js · Razorpay · Custom video gallery",
    title: "ChinkiZ — Custom D2C Creator Storefront · Divyansh Sood",
    description: "Chinki runs a 600K+ YouTube channel. We built her a direct-to-consumer storefront in custom code — no Shopify — with a video gallery that matches her tutorials.",
    ogTitle: "ChinkiZ Knitting Knife — Case study",
    ogDescription: "A custom D2C storefront for a 600K-subscriber YouTuber. No Shopify, no theme — fully owned.",
    ogImage: "https://www.divyanshsood.com/images/work/chinkiz-1.webp",
    keywords: "creator storefront, YouTuber e-commerce, D2C website India, custom Next.js store, Razorpay storefront, video commerce, no Shopify, Divyansh Sood",
    feature: { src: "/images/work/chinkiz-1.webp", alt: "ChinkiZ Knitting Knife — storefront hero on desktop" },
    body: [
      { tag: "The brief", title: "Where buy meets video", type: "prose",
        html: `Chinki tried two e-commerce builders. Both fought the way her audience shops — long tutorial videos, then a comment, then a DM. She wanted a site where the <em>video</em> sits next to the <em>buy button</em>, not buried under it.` },
      { tag: "In her words", type: "quote",
        quote: `"I did not think it could be achieved without going to e-commerce builders and only using custom code."`,
        attribution: "— Chinki, Founder" },
      { tag: "Stack", type: "list", items: ["Next.js", "Razorpay", "Custom video gallery", "Admin panel"] },
      { tag: "What we shipped", title: "A storefront that feels like her tutorials", type: "prose",
        html: `A custom Next.js storefront with <strong>Razorpay</strong>, a <strong>video gallery</strong> mirroring her YouTube grid, and an <strong>admin panel</strong> where she adds products the way she'd add a video — title, thumbnail, done. Zero Shopify themes, zero builder lock-in, full code ownership.` },
      { tag: "The result", title: "The store finally shops the way her audience does", type: "prose",
        html: `Two e-commerce builders had already failed at the same job, because both wanted the video to be a tab and the product to be a row in a grid. Here the demo sits beside the buy button, which is the actual sequence her viewers follow — watch, decide, buy. She publishes new products herself, <strong>in two weeks from brief to live</strong>, and owns the code outright.` },
      { tag: "Why not Shopify", title: "A catalogue can't carry a creator", type: "prose",
        html: `Chinki's audience knows her through tutorials: twenty-minute videos of her hands working through a pattern. A theme built around a photo, a price and an Add to Cart button misses the reason anyone buys from her. So the store puts <strong>the tutorial next to the buy button</strong>, keeps checkout to UPI and cash on delivery with one tap to WhatsApp, is designed for the phone her audience watches on, and runs on infrastructure she owns rather than rents.` },
      { tag: "The lesson", type: "prose",
        html: `A creator's storefront is not a catalogue with videos added. It is the video, with a way to buy attached — and that ordering is exactly what off-the-shelf builders fight you on.` },
    ],
    gallery: [
      { src: "/images/work/chinkiz-1.webp", alt: "ChinkiZ Knitting Knife — storefront hero" },
      { src: "/images/work/chinkiz-2.webp", alt: "ChinkiZ Knitting Knife — product collection grid" },
    ],
    faq: [
      { q: "What is ChinkiZ Knitting Knife?", a: "ChinkiZ Knitting Knife is a direct-to-consumer storefront built by Divyansh Sood Studio for Chinki, a creator with a 600K+ subscriber YouTube channel. The site puts her tutorial videos next to the buy button." },
      { q: "Does the store use Shopify or a website builder?", a: "No. It is fully custom-coded in Next.js with Razorpay payments — zero Shopify themes and zero builder lock-in, so the owner keeps full code ownership." },
      { q: "How does the owner add products?", a: "A custom admin panel lets her add a product the way she'd add a video — title, thumbnail, done — with a video gallery that mirrors her YouTube grid." },
      { q: "What does a creator store need that a normal online store doesn't?", a: "Content and commerce on the same screen, because the tutorials are why people buy. It also needs to be mobile-first, have a simple checkout (UPI, cash on delivery, WhatsApp for questions), look and feel continuous with the channel, and run on infrastructure the creator owns." },
    ],
  },
  {
    slug: "baglamukhi-travels",
    // Design copy for the Portfolio + Case Study templates (brandbook redesign).
    sector: "Travel", tags: "Travel · Local SEO", location: "Kangra, Himachal Pradesh",
    stack: "Astro · JSON-LD", scope: "Local-SEO site, schema graph, WhatsApp booking",
    line: "Owner-drivers competing against commission agents for Kangra's airport transfers and the Devi Darshan yatra — now averaging position 5.7 on Google.",
    brief: "Kapil Dev and Sahil have run cabs out of Kangra as owner-drivers since 2018, but bookings arrived through commission agents who owned the customer relationship.",
    build: ["Astro build with a complete local-business JSON-LD schema graph","llms.txt and one-tap WhatsApp booking","Pages for Gaggal airport transfers and outstation runs","The six-temple Devi Darshan yatra circuit"],
    stats: [["5.7","Avg. Google position, 28 days"],["7.25K","Search impressions"],["148","Clicks in 28 days"]],
    quote: null,
    num: "07", name: "Baglamukhi Travels", category: "Travel · Local SEO", year: "2026",
    liveUrl: "https://baglamukhitravels.com",
    domain: "baglamukhitravels.com",
    headlineTail: "— Kangra taxi & Devi Darshan",
    updated: "2026-09-29",
    stackLine: "Astro · JSON-LD · WhatsApp",
    service: { href: "/services/travel-website-development/", label: "Travel & taxi website development" },
    title: "Baglamukhi Travels — Kangra Taxi Website · Divyansh Sood",
    description: "A family-run Kangra taxi operator up against commission agents and call centres. Custom-built with a full schema graph — now averaging position 5.7 on Google.",
    ogTitle: "Baglamukhi Travels — Kangra taxi & Devi Darshan · Case study",
    ogDescription: "Owner-driver taxi service in Kangra, built to win pilgrimage and airport-transfer search outright.",
    ogImage: "https://www.divyanshsood.com/images/work/baglamukhi-travels-1.webp",
    keywords: "Kangra taxi website, Devi Darshan yatra booking, Himachal cab service website, local SEO travel operator, Astro travel site, WhatsApp booking, schema markup local business, Divyansh Sood",
    feature: { src: "/images/work/baglamukhi-travels-1.webp", alt: "Baglamukhi Travels — Kangra taxi service homepage" },
    body: [
      { tag: "The brief", title: "Cut out the agents, own the search", type: "prose",
        html: `Kangra's taxi trade runs on commission agents and call centres that sit between the traveller and the driver. Kapil and Sahil have been on the road since <strong>2018</strong> with a 5.0 Google rating and valid commercial permits — but no channel they controlled. The site had one job: be the thing that ranks, so the booking arrives directly.` },
      { tag: "Stack", type: "list", items: ["Astro", "Vercel", "JSON-LD graph", "WhatsApp deep-link", "llms.txt"] },
      { tag: "What we shipped", title: "Ten pages, each aimed at a real search", type: "prose",
        html: `Dedicated pages for the intents people actually type — <strong>/devi-darshan</strong> for the six-temple yatra, <strong>/taxi-service</strong> for airport and railway transfers, plus packages, guides and FAQ. <strong>27 point-to-point routes</strong> are published with all-in fares, so the price is answered before anyone has to ask. Underneath sits a complete local-business schema graph: geo-coordinates, opening hours, an offer catalogue with real price specs, FAQ, and the aggregate rating. Booking is a one-tap WhatsApp deep-link to whichever owner is free — no advance, no agent.` },
      { tag: "The result", title: "Position 5.7, from a standing start", type: "prose",
        html: `In a 28-day window the site drew <strong>7.25K impressions</strong> and <strong>148 clicks</strong> at an average position of <strong>5.7</strong> — first-page placement for a single-operator business competing against aggregators. An <code>llms.txt</code> file ships at the root so AI assistants can quote the routes and fares accurately too.` },
      { tag: "Seven weeks in", title: "Publish the fare", type: "prose",
        html: `The site is ten pages, with no blog and no content calendar. The strategy fits in one sentence: <strong>publish the fare</strong>. Twenty-seven point-to-point routes each state an all-in price as text on the page, because people type “gaggal airport to dharamshala taxi fare”, and a page that says “call for quote” has no number to match. In its first seven weeks the site drew <strong>19,100 impressions and 261 clicks at an average position of 5.4</strong>, with the curve at its steepest in the final week.` },
      { tag: "The honest part", title: "Rank is not traffic", type: "prose",
        html: `A 1.4% click-through rate at position 5.4 is roughly a quarter of what that position used to earn. On a phone, a map pack, an AI overview and aggregator listings now sit above the organic results. The fix isn't to chase rank harder. It's to be the result that gets picked out of a crowded page: the fare in the snippet, <a href="/blog/rank-on-google-maps-himachal/">reviews in the map pack</a>, and facts structured well enough that an AI overview names you.` },
    ],
    gallery: [
      { src: "/images/work/baglamukhi-travels-1.webp", alt: "Baglamukhi Travels — homepage hero" },
      { src: "/images/work/baglamukhi-travels-2.webp", alt: "Baglamukhi Travels — Devi Darshan yatra circuit" },
    ],
    faq: [
      { q: "What is Baglamukhi Travels?", a: "Baglamukhi Travels is a family-run taxi and tour operator in Kangra, Himachal Pradesh, run by owner-drivers Kapil Dev and Sahil since 2018. Divyansh Sood Studio built their website on Astro with a full local-business schema graph and WhatsApp booking." },
      { q: "How does the site perform in search?", a: "It averages position 5.7 on Google, drawing 7.25K impressions and 148 clicks in a 28-day window — first-page placement for a single-operator business competing against travel aggregators." },
      { q: "What stack does Baglamukhi Travels run on?", a: "Astro on Vercel, with a JSON-LD local-business graph, an llms.txt file for AI search, and one-tap WhatsApp deep-links instead of a booking gateway." },
      { q: "Why publish your prices when competitors hide theirs behind a phone call?", a: "Because the person searching is trying to answer a price question, and a page that answers it is the page that gets returned and quoted. Twenty-seven point-to-point routes published with all-in fares means twenty-seven pages of specific, matchable text against queries like \"Gaggal airport to Dharamshala taxi fare\". Hiding the number behind \"call for quote\" means the page has nothing to match against, and a competitor's page answers instead. The commercial objection — that competitors will see your prices — assumes they can't already call and ask." },
      { q: "Why is the click-through rate only 1.4% at that position?", a: "Because the organic result is no longer the first thing on the page. For local and travel queries, Google shows a map pack, an AI overview, aggregator listings and often paid results above the organic block. A position of 5.4 can easily sit below all of that. The impressions still matter — they are proof the pages match real demand — but treating position as a proxy for traffic is the mistake. Measure clicks and enquiries, not rank." },
      { q: "Do you need a big content operation to rank a local business?", a: "No. This is a ten-page site. What it has instead of volume is specificity: every page answers one real question a customer types, with the actual answer on the page rather than a form to request it. Ten pages that each match a distinct intent will outperform fifty pages that all say roughly the same thing about a company's commitment to quality service." },
    ],
  },
  {
    slug: "sunny-himachal-travels",
    // Design copy for the Portfolio + Case Study templates (brandbook redesign).
    sector: "Travel", tags: "Travel · Tours & Taxi", location: "Dharamshala, Himachal Pradesh",
    stack: "Astro · Content collections", scope: "76 route, destination and transfer pages",
    line: "A page for every trip, transfer and town — 1.1 KB of JavaScript and Lighthouse 100 on all four desktop scores.",
    brief: "A Dharamshala tour operator arrived with a one-page design canvas relying on a 69 KB runtime.",
    build: ["25 tour routes, 28 destinations, 14 transfers, 9 local searches","Build fails if any colour pair drops below WCAG AA","Duplication test rejects near-identical pages","Drafts stay noindex until verified"],
    stats: [["1.1KB","JavaScript, gzipped"],["100","Lighthouse × 4, desktop"],["76","Landing pages"]],
    quote: null,
    num: "11", name: "Sunny Himachal Travels", category: "Travel · Tours & Taxi", year: "2026",
    liveUrl: "https://www.sunnyhimachaltravels.com",
    domain: "sunnyhimachaltravels.com",
    headlineTail: "— Dharamshala tours & taxi",
    updated: "2026-09-29",
    stackLine: "Astro · TypeScript · Content collections · Playwright + axe",
    service: { href: "/services/travel-website-development/", label: "Travel & taxi website development" },
    title: "Sunny Himachal Travels — Tour & Taxi Website · Divyansh Sood",
    description: "A tour and taxi website for a Dharamshala operator: a page for every trip, transfer and town, 1.1 KB of JavaScript, and 100 on all four Lighthouse scores on desktop.",
    ogTitle: "Sunny Himachal Travels — tours & taxi website · Case study",
    ogDescription: "A page for every trip, transfer and town. 1.1 KB of JavaScript. Lighthouse 100 ×4.",
    ogImage: "https://www.divyanshsood.com/images/work/sunny-himachal-travels-1.webp",
    keywords: "travel agency website Himachal, taxi website developer, tour operator website Dharamshala, Himachal tour packages website, Astro travel site, WhatsApp enquiry form, Divyansh Sood",
    feature: { src: "/images/work/sunny-himachal-travels-1.webp", alt: "Sunny Himachal Travels — homepage hero with the WhatsApp trip-planning button" },
    body: [
      { tag: "The brief", title: "A good design that wasn't a website", type: "prose",
        html: `The canvas was finished and its copy was genuinely good: plain, specific, no brochure language. So it was carried across word for word. Underneath, though, every style was an inline string, interactivity ran through a <strong>69 KB runtime</strong>, and images were empty placeholders. The job was to turn that one page into a site that ranks for what travellers actually search: a trip, a route, a town.` },
      { tag: "Stack", type: "list", items: ["Astro, static output", "TypeScript (strict)", "Content collections + Zod", "Hand-written CSS tokens", "Vitest, Playwright + axe"] },
      { tag: "Guardrails", title: "Nothing ships unchecked", type: "prose",
        html: `A page is a draft until it's marked <code>verified</code>. Drafts render at their URL for checking, but they're <code>noindex</code> and left out of the sitemap. Prices have a separate confirmation flag. The build fails if any colour pair drops below WCAG AA.` },
      { tag: "What we shipped", title: "One page per search", type: "prose",
        html: `There are <strong>25 tour routes</strong>, <strong>28 destinations</strong>, <strong>14 point-to-point transfers</strong>, <strong>9 local “taxi in &lt;town&gt;” pages</strong>, 7 planning guides and a blog, all written as Markdown with typed frontmatter. The link graph is reciprocal: name a region on a trip and the trip appears on the region's page, with no one editing it. The enquiry form writes the WhatsApp message for the traveller, and a sticky bar keeps WhatsApp and Call one tap away on a phone.` },
      { tag: "Duplicate content", title: "A build that refuses thin pages", type: "prose",
        html: `Growing from one page to about a hundred is exactly where travel sites go thin. A build test compares every pair of pages on five-word shingles and <strong>fails above 0.23 similarity</strong>. The most similar pair on the site scores 0.077. Routes that would have overlapped an existing page were dropped instead of being written thin.` },
      { tag: "The lesson", type: "prose",
        html: `A travel site ranks one page at a time. Someone typing “taxi service in Palampur” wants the Palampur page, not the homepage.` },
    ],
    gallery: [
      { src: "/images/work/sunny-himachal-travels-1.webp", alt: "Sunny Himachal Travels — homepage hero" },
      { src: "/images/work/sunny-himachal-travels-2.webp", alt: "Sunny Himachal Travels — the Big Himachal Loop tour page" },
    ],
    mobileShots: [
      { src: "/images/work/sunny-himachal-travels-mobile-1.webp", alt: "Sunny Himachal Travels homepage on a phone" },
      { src: "/images/work/sunny-himachal-travels-mobile-2.webp", alt: "Sunny Himachal Travels taxi page on a phone, with the sticky WhatsApp and Call bar" },
    ],
    faq: [
      { q: "What is Sunny Himachal Travels?", a: "Sunny Himachal Travels is a private tour and taxi operator based in Dharamshala, Himachal Pradesh, running customised trips and point-to-point transfers across the state. Divyansh Sood designed and built its website on Astro." },
      { q: "How fast is the Sunny Himachal Travels website?", a: "It ships 1.1 KB of JavaScript, gzipped, and scores 100 for performance, accessibility, best practices and SEO in Lighthouse on desktop." },
      { q: "How do travellers book?", a: "The enquiry form turns the trip details into a pre-written WhatsApp message to the operator. On phones, a sticky bar keeps WhatsApp and Call one tap away." },
    ],
  },
  {
    slug: "yash-rock-hotel",
    // Design copy for the Portfolio + Case Study templates (brandbook redesign).
    sector: "Hospitality", tags: "Hospitality · Hotel", location: "Dehrian, Kangra",
    stack: "Next.js · Custom design system", scope: "Hotel site, near pages, local guides",
    line: "A seven-room hillside hotel with no booking engine by design — every enquiry goes to WhatsApp or a call.",
    brief: "The owner confirms bookings personally and rates vary, so a generic booking-engine prototype was the wrong product.",
    build: ["14 “near” pages for where guests are headed","19 local guides","~3 MB of homepage video removed for hill mobile data","Hotel, Restaurant and pool structured data"],
    stats: [["7","Rooms"],["14","“Near” pages"],["19","Local guides"]],
    quote: null,
    num: "12", name: "Yash Rock Hotel", category: "Hospitality · Hotel", year: "2026",
    liveUrl: "https://www.yashrockhotel.com",
    domain: "yashrockhotel.com",
    headlineTail: "— hillside hotel & pool, Kangra",
    updated: "2026-09-29",
    stackLine: "Next.js 16 · TypeScript · Custom design system · ImageKit",
    service: { href: "/services/hotel-website-development/", label: "Hotel & homestay website development" },
    title: "Yash Rock Hotel — Hotel Website, Kangra · Divyansh Sood",
    description: "Website for a seven-room hillside hotel with a pool in Kangra: no booking engine, enquiries go to WhatsApp, and 14 “near” pages reach guests by destination.",
    ogTitle: "Yash Rock Hotel — hillside hotel website · Case study",
    ogDescription: "A seven-room hotel in Kangra. No booking engine, no OTA links: built to make people message.",
    ogImage: "https://www.divyanshsood.com/images/work/yash-rock-hotel-1.webp",
    keywords: "hotel website design Himachal, hotel website Kangra, homestay website developer, WhatsApp booking hotel website, direct booking website India, Next.js hotel site, Divyansh Sood",
    feature: { src: "/images/work/yash-rock-hotel-1.webp", alt: "Yash Rock Hotel — aerial hero of the hillside pool at sunset with WhatsApp and Call buttons" },
    body: [
      { tag: "The brief", title: "Replace the brief, not just the styling", type: "prose",
        html: `A booking engine is the default for a hotel website, and it was the wrong one here. Seven rooms of one type, rates that move, and an owner who closes bookings on the phone. The site's job is to make a visitor <em>want to be there</em>, then put WhatsApp in reach. Every fact sits in one verified table, and anything unconfirmed shipped with a visible “needs confirming” marker until the owner answered.` },
      { tag: "Stack", type: "list", items: ["Next.js 16 (App Router)", "TypeScript", "Design system, 25 primitives", "ImageKit AVIF / WebP", "Hotel + Restaurant + Pool schema"] },
      { tag: "Honesty", title: "The rooftop page, rebuilt", type: "prose",
        html: `The rooftop was first written as a party venue anyone could hire. The owner said it isn't: it belongs to whoever is staying that night. The page was rebuilt around that, so the search result now says “for groups who stay”, and the hotel should stop getting calls it has to turn down.` },
      { tag: "Local search", title: "Pages for where guests are going", type: "prose",
        html: `Nobody searches for “hotel in Dehrian”. They search for somewhere to stay near what they came for: <strong>NIFT Kangra, Tanda Medical College, Kangra Airport</strong>, the temples, the cricket stadium. That's 14 “near” pages, each written about its place, plus 19 local guides on the blog. The footer gives each page a link from every page on the site, so none are orphaned.` },
      { tag: "Performance", title: "Cutting the video", type: "prose",
        html: `The site had a drone-pass hero, a lightbox and looping clips, about <strong>3 MB of video on every homepage load</strong> for a hill with patchy mobile data. All of it came out on the owner's call. The masters are kept, so it's reversible. Photographs stream from ImageKit as AVIF and WebP, and a design-system adherence check runs with every build.` },
      { tag: "The lesson", type: "prose",
        html: `A small hotel's website doesn't need to take bookings. It needs to make someone message you.` },
    ],
    gallery: [
      { src: "/images/work/yash-rock-hotel-1.webp", alt: "Yash Rock Hotel — homepage hero over the pool and terraced fields" },
      { src: "/images/work/yash-rock-hotel-2.webp", alt: "Yash Rock Hotel — the pool page for day visitors and guests" },
    ],
    mobileShots: [
      { src: "/images/work/yash-rock-hotel-mobile-1.webp", alt: "Yash Rock Hotel homepage on a phone with WhatsApp and Call buttons" },
      { src: "/images/work/yash-rock-hotel-mobile-2.webp", alt: "Yash Rock Hotel rooms page on a phone" },
    ],
    faq: [
      { q: "What is Yash Rock Hotel's website?", a: "It is the website of Yash Rock Hotel & Swimming Pool, a seven-room hillside hotel in Dehrian, Kangra, Himachal Pradesh. Divyansh Sood designed and built it on Next.js 16 with a custom design system." },
      { q: "Why doesn't the hotel website have a booking engine?", a: "The hotel has one room type and rates that vary, and the owner confirms bookings personally. Every call to action goes to WhatsApp or a phone call instead, with no OTA commission and no booking form." },
      { q: "How does a small hotel website rank locally?", a: "Yash Rock's site has 14 'near' pages for the places guests are travelling to, such as NIFT Kangra, Tanda Medical College and Kangra Airport, plus 19 local guides. It also publishes Hotel, Restaurant and swimming-pool structured data." },
    ],
  },
  {
    slug: "pinnacle-world-school",
    // Design copy for the Portfolio + Case Study templates (brandbook redesign).
    sector: "Education", tags: "Education · CBSE", location: "Baroh, Kangra",
    stack: "Next.js 16 · React 19", scope: "CBSE school website, WhatsApp admissions",
    line: "A CBSE school website where every published fact traces back to the affiliation record — nothing invented.",
    brief: "The governing rule was simple: every fact lives in one file with its source beside it, and any gap shows “To be updated” rather than a guess.",
    build: ["Mandatory Public Disclosure per Appendix IX","Admission and contact forms that open WhatsApp","Static prerender on Vercel","All 14 old URLs 308-redirected"],
    stats: [["14","Old URLs redirected"],["0","Invented facts"],["N–X","Classes covered"]],
    quote: null,
    num: "10", name: "Pinnacle World School", category: "Education · CBSE", year: "2026",
    liveUrl: "https://www.pinnacleworldschool.co.in",
    domain: "pinnacleworldschool.co.in",
    headlineTail: "— CBSE school website, Kangra",
    updated: "2026-09-29",
    stackLine: "Next.js 16 · React 19 · TypeScript · Vercel",
    service: { href: "/services/school-website-development/", label: "School website development" },
    title: "Pinnacle World School — CBSE School Website, Kangra · Divyansh Sood",
    description: "A CBSE school website for Pinnacle World School, Baroh (Kangra): Mandatory Public Disclosure, admissions over WhatsApp, and not one published fact without a source.",
    ogTitle: "Pinnacle World School — CBSE school website · Case study",
    ogDescription: "A CBSE school site in Kangra where every published fact traces back to a source.",
    ogImage: "https://www.divyanshsood.com/images/work/pinnacle-world-school-1.webp",
    keywords: "CBSE school website, school website developer Himachal, school website Kangra, mandatory public disclosure page, school admissions enquiry form, Next.js school website, Divyansh Sood",
    feature: { src: "/images/work/pinnacle-world-school-1.webp", alt: "Pinnacle World School — homepage with admissions banner and campus carousel" },
    body: [
      { tag: "The brief", title: "A new domain, and a stricter rule", type: "prose",
        html: `The school was leaving a hosted school-CMS for its own site at <strong>pinnacleworldschool.co.in</strong>. Some of the old content could not be confirmed, and on a CBSE school site a wrong number is worse than a missing one: the Mandatory Public Disclosure is read by parents <em>and</em> by the board. So facts live in one file, each with its source written next to it, and every page, footer and schema node reads from there.` },
      { tag: "Stack", type: "list", items: ["Next.js 16 (App Router)", "React 19 + TypeScript", "Static prerender on Vercel", "WhatsApp form hand-off", "JSON content + admin panel"] },
      { tag: "Admissions", title: "Forms without a backend", type: "prose",
        html: `The admission, contact and alumni forms validate in the browser, then open WhatsApp with the message already written to the school office. There's no database and nothing is stored. The office already works in WhatsApp, so enquiries arrive there.` },
      { tag: "What we shipped", title: "Every page CBSE asks for", type: "prose",
        html: `Mandatory Public Disclosure laid out as Appendix IX of the affiliation bye-laws, with a summary card of the school's CBSE record, a sticky section index and a print stylesheet. Transfer certificates, committees, faculty, results, fees, the academic calendar, transport, downloads and the anti-bullying policy each get their own page. A disclosure row reads <strong>“Document awaited”</strong> until the PDF lands, then turns into a “View PDF” link with a one-line change.` },
      { tag: "The build", title: "The school's own photographs, served light", type: "prose",
        html: `Only the school's own photographs, gathered from its YouTube and Facebook and cut into <strong>AVIF and WebP</strong>. The four stock images the old site used are skipped by the image script. The phone hero is a 640px AVIF, and the first load comes in at about 500 KB. Every page has exactly one H1 and passes WCAG AA contrast. The affiliation number and school code are written into the <code>School</code> schema, and all 14 old URLs 308 to their new pages, so existing links and bookmarks still work.` },
      { tag: "The lesson", type: "prose",
        html: `On a school website, “To be updated” is a feature. A parent forgives a gap. An inspection doesn't forgive a wrong figure.` },
    ],
    gallery: [
      { src: "/images/work/pinnacle-world-school-1.webp", alt: "Pinnacle World School — homepage hero with CBSE affiliation details" },
      { src: "/images/work/pinnacle-world-school-2.webp", alt: "Pinnacle World School — admissions page with the three-step apply process" },
    ],
    mobileShots: [
      { src: "/images/work/pinnacle-world-school-mobile-1.webp", alt: "Pinnacle World School homepage on a phone, with the four-action bottom bar" },
      { src: "/images/work/pinnacle-world-school-mobile-2.webp", alt: "Pinnacle World School Mandatory Public Disclosure page on a phone" },
    ],
    faq: [
      { q: "What is Pinnacle World School's website?", a: "It is the official site of Pinnacle World School, Baroh, a CBSE-affiliated school in Kangra district, Himachal Pradesh (affiliation no. 630225), teaching Nursery to Class X. Divyansh Sood designed and built it on Next.js 16 and maintains it." },
      { q: "Does the site include the CBSE Mandatory Public Disclosure?", a: "Yes. It follows Appendix IX of the CBSE affiliation bye-laws, with a summary of the school's CBSE record, a section index and a print stylesheet. Each document row shows 'Document awaited' until the school supplies the PDF." },
      { q: "How do admission enquiries work?", a: "The admission form validates in the browser, then opens WhatsApp with the enquiry already written to the school office's number. The site has no backend and stores no personal data." },
    ],
  },
  {
    slug: "webseek",
    // Design copy for the Portfolio + Case Study templates (brandbook redesign).
    sector: "AI", tags: "AI · Product", location: "Worldwide",
    stack: "React · Tailwind · Claude · GPT · Gemini", scope: "Own product — AI website generator",
    line: "One prompt to a deployed, custom-coded site — running on Claude, GPT and Gemini in production behind one picker.",
    brief: "The studio's bet on where agencies go next: one credit, one prompt, any input language, and a working site the user owns.",
    build: ["Three model providers in production","Output is HTML the user owns","Any input language","Live beta with five free credits"],
    stats: [["3","Model providers, live"],["1","Prompt to deploy"],["5","Free credits per user"]],
    quote: null,
    num: "06", name: "WebSeek.ai", category: "AI Product", year: "2026",
    liveUrl: "https://ai-website-generator-tan.vercel.app",
    domain: "ai-website-generator-tan.vercel.app",
    headlineTail: "— AI website builder",
    updated: "2026-07-28",
    stackLine: "React · Tailwind · Anthropic / OpenAI / Google",
    title: "WebSeek.ai — AI Website Builder · Divyansh Sood",
    description: "WebSeek.ai — our own bet on where agencies go next. One credit, one prompt, any language. Custom-coded output paired with Claude, GPT and Gemini.",
    ogTitle: "WebSeek.ai — AI website builder · Case study",
    ogDescription: "Our own bet on where agencies go next. One credit, one prompt, any language.",
    ogImage: "https://www.divyanshsood.com/images/work/webseek-1.webp",
    keywords: "AI website builder, AI website generator, prompt to website, Claude GPT Gemini website, custom-coded AI site, React Tailwind, Divyansh Sood",
    feature: { src: "/images/work/webseek-1.webp", alt: "WebSeek.ai — the prompt bar and model picker on desktop" },
    body: [
      { tag: "The bet", title: "Custom output, not block-assembled templates", type: "prose",
        html: `Most "AI website builders" produce identical, sectioned-template marketing pages. We built the opposite: <em>custom-coded output</em>, plus a model picker — Claude for taste, GPT for breadth, Gemini for speed.` },
      { tag: "Audience", type: "list",
        items: ["SMEs without a developer", "Designers wanting a draft fast", "Our own studio — dog food"] },
      { tag: "Stack", type: "list",
        items: ["React + Tailwind", "Anthropic SDK", "OpenAI SDK", "Google AI"] },
      { tag: "The result", title: "Three providers in production, behind one prompt bar", type: "prose",
        html: `WebSeek runs <strong>Claude, GPT and Gemini side by side in a live product</strong>, not a demo — which means the differences between them are something I've had to handle in production: prompt shapes that work on one and not another, failure modes, cost and latency trade-offs. That experience is the reason AI features on client projects are reused code rather than an experiment billed to the client. The product is in active iteration and the output stays <em>ownable HTML</em>.` },
      { tag: "The lesson", type: "prose",
        html: `Running your own product changes how you scope other people's. Every estimate I give now comes from having paid the cost of being wrong on something I owned.` },
    ],
    gallery: [
      { src: "/images/work/webseek-1.webp", alt: "WebSeek.ai — prompt bar with the Claude, GPT and Gemini model picker" },
      { src: "/images/work/webseek-2.webp", alt: "WebSeek.ai — choosing a model before generating a site" },
      { src: "/images/work/webseek-3.webp", alt: "WebSeek.ai — generated site preview, ready to deploy" },
    ],
    // Mobile screenshots — drop phone-sized images into /public/images/work,
    // run scripts/gen-work-variants.mjs, and list them here to render a framed
    // "On mobile" gallery on this case study. Leave [] and nothing shows. Any
    // project below can use the same field, e.g.:
    //   mobileShots: [{ src: "/images/work/webseek-mobile-1.webp", alt: "… on a phone" }],
    mobileShots: [],
    faq: [
      { q: "What is WebSeek.ai?", a: "WebSeek.ai is an AI website generator built by Divyansh Sood Studio. You give it one prompt in any language and it returns a custom-coded website, with a model picker for Claude, GPT or Gemini." },
      { q: "Is WebSeek.ai free to try?", a: "Yes — every new user gets 5 free credits while the product is in active iteration. The output is ownable HTML, not locked inside a SaaS editor." },
      { q: "Which technologies power WebSeek.ai?", a: "React and Tailwind on the front end, with the Anthropic, OpenAI and Google AI SDKs powering the generation." },
    ],
  },
  {
    slug: "northpeak",
    // Design copy for the Portfolio + Case Study templates (brandbook redesign).
    sector: "Web app", tags: "Portal · Solar", location: "Himachal Pradesh",
    stack: "Angular", scope: "15-page site, gallery, calendar, admin",
    line: "A government-sector solar contractor gets a private-sector pitch — 15 pages, all editable by the team.",
    brief: "A contractor doing mostly government work needed to break into a private sector dominated by competitors with digital presence.",
    build: ["15-page Angular site","Project gallery and work calendar","Dashboard-cum-admin panel","Case studies published without a developer"],
    stats: [["15","Editable pages"],["0","Dev tickets to edit"],["1","New private-sector pitch"]],
    quote: ["Exactly what we wanted. I will refer Divyansh within my circle for life.","Founder, North Peak Power Systems"],
    // Personal project — shown on /portfolio under "Personal projects", kept off the homepage deck.
    num: "08", name: "North Peak Power Systems", category: "Infra · Dashboard", year: "2025",
    liveUrl: "https://northpeakpowersystems.vercel.app/",
    domain: "northpeakpowersystems.vercel.app",
    headlineTail: "— solar contractor portal",
    updated: "2026-07-28",
    stackLine: "Angular · Project gallery · Admin",
    title: "North Peak — Solar Contractor Website · Divyansh Sood",
    description: "Himachal electrical & solar contractor breaking into the private sector. 15-page Angular site with project gallery, work calendar and self-serve admin.",
    ogTitle: "North Peak Power Systems — solar contractor portal · Case study",
    ogDescription: "15-page Angular site + dashboard-cum-admin for a Himachal electrical/solar contractor breaking into the private sector.",
    ogImage: "https://www.divyanshsood.com/images/work/northpeak-1.webp",
    keywords: "solar contractor website, electrical contractor portal, Angular website, project gallery, admin dashboard, Himachal solar, government to private, Divyansh Sood",
    feature: { src: "/images/work/northpeak-1.webp", alt: "North Peak Power Systems — homepage hero on desktop" },
    body: [
      { tag: "The brief", title: "Govt → private. With proof, not promises.", type: "prose",
        html: `The team was excellent at government tenders but invisible in the private market — where buyers want photos, recent projects and a clear pitch. The site had to <em>showcase work</em> credibly and let the team add new case studies themselves, not via a developer.` },
      { tag: "In their words", type: "quote",
        quote: `"Divyansh, exactly yahi chahiye tha. Humne pehle jisse karwaya tha vo sirf photos laga ke chala gaya. Mein apne circle mein lifetime zaroor refer karunga."`,
        attribution: "— Founder, North Peak Power Systems" },
      { tag: "Stack", type: "list", items: ["Angular", "Project gallery", "Work calendar", "Custom admin"] },
      { tag: "What we shipped", title: "15 pages + a dashboard the team actually uses", type: "prose",
        html: `Service pages for solar, electrical and infra. A <strong>project gallery</strong> they update without dev help. A work calendar so prospects can see active engagements. A <strong>dashboard-cum-admin</strong> for new uploads — designed for a non-technical operator.` },
      { tag: "The result", title: "Proof that keeps accumulating without me", type: "prose",
        html: `Private-sector buyers judge a contractor on recent, visible work — exactly what a government-tender track record fails to show. The team now <strong>publishes each completed job themselves</strong>, so the portfolio grows every month instead of ageing until someone budgets for a website refresh. Their last developer, in the founder's words above, "just put up photos and left"; the difference here is that the site is theirs to run.` },
      { tag: "The lesson", type: "prose",
        html: `For a proof-driven business, the admin panel <em>is</em> the deliverable. A beautiful site nobody can update is a brochure with a hosting bill.` },
    ],
    gallery: [
      { src: "/images/work/northpeak-1.webp", alt: "North Peak Power Systems — homepage hero" },
      { src: "/images/work/northpeak-2.webp", alt: "North Peak Power Systems — services overview" },
    ],
    faq: [
      { q: "What is North Peak Power Systems?", a: "North Peak Power Systems is a Himachal electrical and solar contractor. Divyansh Sood Studio built a 15-page Angular site with a project gallery, work calendar and a dashboard-cum-admin to help them break into the private sector." },
      { q: "Can the team publish new projects without a developer?", a: "Yes — a dashboard-cum-admin, designed for a non-technical operator, lets the team upload new project case studies and update the gallery themselves." },
      { q: "What framework was used?", a: "Angular, across all 15 pages, with a custom admin dashboard." },
    ],
  },
  {
    slug: "nandini",
    // Design copy for the Portfolio + Case Study templates (brandbook redesign).
    sector: "Travel", tags: "Travel · Taxi", location: "Kangra, Himachal Pradesh",
    stack: "Next.js", scope: "Rebuild, booking form, packages",
    line: "Kangra's most positively reviewed taxi operator stopped losing every lead to Google Maps.",
    brief: "The website was down entirely and every lead was leaking to Google Maps.",
    build: ["On-site booking form","WhatsApp CTA on every package","Outstation packages across North India","Airport-pickup option"],
    stats: [["10×","“More premium than competitors”"],["1","Owned booking funnel"],["0","Leads lost to Maps"]],
    quote: ["Looks 10 times more premium than our competitors. We started getting direct bookings instead of losing them to Google Maps.","Founder, Nandini Travels"],
    num: "04", name: "Nandini Travels", category: "Travel · Local", year: "2025",
    liveUrl: "https://www.nandinitravel.com/",
    domain: "nandinitravel.com",
    headlineTail: "— Kangra taxi operator",
    updated: "2026-09-29",
    stackLine: "Next.js · WhatsApp · Booking form",
    title: "Nandini Travels — Kangra Taxi Booking Site · Divyansh Sood",
    description: "Kangra's most-reviewed taxi operator had a broken site and zero direct bookings — all leads via Google Maps. Rebuilt in Next.js with on-site booking + WhatsApp.",
    ogTitle: "Nandini Travels — Kangra taxi operator · Case study",
    ogDescription: "Next.js rebuild for Kangra's most-reviewed taxi operator. Direct bookings now flow through the site instead of Google Maps.",
    ogImage: "https://www.divyanshsood.com/images/work/nandini-1.webp",
    keywords: "Kangra taxi website, taxi operator website India, travel booking form, WhatsApp booking, Next.js travel site, direct bookings, Google Maps alternative, Divyansh Sood",
    feature: { src: "/images/work/nandini-1.webp", alt: "Nandini Travels — Kangra taxi operator homepage hero" },
    // No "10x" tile here on purpose: that figure comes from the founder's own
    // words below and is a subjective impression, not a measurement. It reads
    // as data in a metric tile, so it stays in the quote where it belongs.
    body: [
      { tag: "The brief", title: "Best reviews in Kangra. Worst funnel.", type: "prose",
        html: `Nandini Travels has the strongest review profile of any taxi operator in Kangra — but every booking arrived through Google Maps, and the old website was down. There was no funnel they owned. Margins shrank with every Maps-driven enquiry.` },
      { tag: "In their words", type: "quote",
        quote: `"The website is so beautiful — looks 10 times more premium than our competitors. We started getting direct bookings instead of losing them to Google Maps."`,
        attribution: "— Founder, Nandini Travels" },
      { tag: "Stack", type: "list", items: ["Next.js", "WhatsApp deep-link", "Booking form", "Vercel"] },
      { tag: "What we shipped", title: "A funnel they own — built around the WhatsApp moment", type: "prose",
        html: `A Next.js rebuild with an <strong>on-site booking form</strong>, a one-tap WhatsApp CTA on every package, outstation routes across North Indian states, and an airport-pickup flow. Faster than the old site. Mobile-first because almost every booking starts on a phone.` },
      { tag: "The result", title: "The best reviews in Kangra finally have somewhere to land", type: "prose",
        html: `Enquiries now arrive on a site the operator controls instead of a Maps listing that could be reordered by Google at any time. The strongest review profile in the district was previously feeding a channel someone else owned — the rebuild turned it into <strong>direct bookings against their own brand</strong>. The founder's read on the change is in their words above; it's an impression rather than a measurement, and it's presented that way.` },
      { tag: "Why a website", title: "Maps builds trust. Search picks the site.", type: "prose",
        html: `Google Maps reviews build local trust, but the search that happens before anyone opens Maps rewards websites. Someone typing “taxi from Kangra to Manali” or “Dharamshala airport pickup” is shown web pages, not a listing. Before the rebuild, the path was Maps → a competitor's site → a competitor's booking. After it, it's Maps → the Nandini Travels site → their WhatsApp → a confirmed booking. Same customer, same intent, different outcome, because there was finally somewhere to land.` },
      { tag: "The lesson", type: "prose",
        html: `Great reviews are not a funnel. If the only place they exist is a platform's listing, the platform decides who sees them — and takes the relationship with the customer.` },
    ],
    gallery: [
      { src: "/images/work/nandini-1.webp", alt: "Nandini Travels — homepage hero" },
      { src: "/images/work/nandini-2.webp", alt: "Nandini Travels — authorised-operator credentials" },
    ],
    faq: [
      { q: "What is Nandini Travels?", a: "Nandini Travels is Kangra's most-positively-reviewed taxi operator. Divyansh Sood Studio rebuilt their website in Next.js with an on-site booking form, a WhatsApp CTA, outstation packages and airport pickup." },
      { q: "Why did the site need rebuilding?", a: "Every booking used to arrive through Google Maps and the old site was down, so the operator owned no funnel. After the rebuild, direct bookings now flow through the site." },
      { q: "What did the founder say about the result?", a: "“The website is so beautiful — looks 10 times more premium than our competitors. We started getting direct bookings instead of losing them to Google Maps.”" },
      { q: "Why does a taxi operator with good Google reviews still need a website?", a: "Reviews on Google Maps build trust, but searches like “taxi from Kangra to Manali” show web pages rather than a Maps listing. Without a site, the operator is invisible to that whole category of search, and the customers who do find the listing get sent to a competitor's site to book." },
    ],
  },
  {
    slug: "dharamshala-tours",
    // Design copy for the Portfolio + Case Study templates (brandbook redesign).
    sector: "Travel", tags: "Travel · WhatsApp-first", location: "Kangra, Himachal Pradesh",
    stack: "Astro · CMS", scope: "Mobile-first booking flow, CMS",
    line: "A WhatsApp-first booking flow, part of roughly 1,000 travel packages booked every month.",
    brief: "Three school friends running a travel business needed a booking flow that matched how their customers actually behave.",
    build: ["WhatsApp flow with the package pre-filled","Built mobile-first — 95%+ of traffic is phones","CMS so the team publishes itineraries","Skipped the accommodation-listing pattern"],
    stats: [["~1,000","Packages booked monthly"],["95%+","Traffic on phones"],["0","Devs to add a trip"]],
    quote: null,
    // Personal project — shown on /portfolio under "Personal projects", kept off the homepage deck.
    num: "09", name: "Dharamshala Tours", category: "Travel · CMS", year: "2025",
    liveUrl: "https://dharamshalatours.in",
    domain: "dharamshalatours.in",
    headlineTail: "— WhatsApp-first travel",
    updated: "2026-07-28",
    stackLine: "Astro · CMS · WhatsApp",
    service: { href: "/services/travel-website-development/", label: "Travel & taxi website development" },
    title: "Dharamshala Tours — Travel Booking Site · Divyansh Sood",
    description: "Three school friends in Kangra, one WhatsApp-first booking flow. Skipped the accommodation-listing pattern. Part of ~1,000 packages booked monthly.",
    ogTitle: "Dharamshala Tours — Case study",
    ogDescription: "WhatsApp-first booking flow for a Kangra travel operator. ~1,000 packages a month.",
    ogImage: "https://www.divyanshsood.com/images/work/dharamshala-tours-1.webp",
    keywords: "Dharamshala tours, Kangra travel website, WhatsApp booking, travel packages Himachal, Astro CMS website, travel operator website India, Divyansh Sood",
    feature: { src: "/images/work/dharamshala-tours-1.webp", alt: "Dharamshala Tours — homepage hero on desktop" },
    body: [
      { tag: "The brief", title: "Sell packages, not hotel listings", type: "prose",
        html: `Every Kangra travel operator runs the same template — a list of hotels with prices, a contact form nobody fills. The founders wanted to be different: they sell <em>packages</em>, not rooms, and most of conversion happens on WhatsApp.` },
      { tag: "Stack", type: "list", items: ["Astro", "WhatsApp deep-link", "Headless CMS", "Vercel"] },
      { tag: "What we shipped", title: "Built around the WhatsApp moment", type: "prose",
        html: `Each package page ends in a <strong>one-tap WhatsApp deep link</strong> with the package pre-filled. The CMS lets the team push a new monsoon or winter itinerary without waiting on a developer. Mobile-first because 95%+ of their traffic is on phones.` },
      { tag: "The result", title: "~1,000 packages a month, booked in a chat", type: "prose",
        html: `The site is part of roughly <strong>1,000 travel packages booked every month</strong>. It gets there by refusing the pattern every competitor copies: no hotel-listing grid, no contact form that goes nowhere. The booking ends where the customer already is — a WhatsApp thread with the package name already typed — and the team publishes seasonal itineraries themselves as demand shifts.` },
      { tag: "The lesson", type: "prose",
        html: `Match the funnel to where the conversation actually happens. A form is not neutral — in this market it is a worse WhatsApp button.` },
    ],
    gallery: [
      { src: "/images/work/dharamshala-tours-1.webp", alt: "Dharamshala Tours — homepage hero" },
      { src: "/images/work/dharamshala-tours-2.webp", alt: "Dharamshala Tours — seasonal guide" },
    ],
    faq: [
      { q: "What is Dharamshala Tours?", a: "Dharamshala Tours is a WhatsApp-first travel booking site for a Kangra operator run by three school friends, built by Divyansh Sood Studio. It sells travel packages rather than hotel listings." },
      { q: "How do customers book a trip?", a: "Every package page ends in a one-tap WhatsApp deep link with the package pre-filled, because most conversion happens on WhatsApp. The site is part of roughly 1,000 packages booked each month." },
      { q: "Can the team add new packages themselves?", a: "Yes — a headless CMS lets the team publish a new monsoon or winter itinerary without waiting on a developer." },
    ],
  },
];
