/* ===========================================================================
   Project case-study data (content only). Pure data — no rendering logic.
   The HTML renderer + JSON-LD live in ./render.mjs.
   =========================================================================== */

export { SITE } from "../site.mjs";

export const projects = [
  {
    slug: "webseek",
    num: "06", name: "WebSeek.ai", category: "AI Product", year: "2026",
    liveUrl: "https://ai-website-generator-tan.vercel.app",
    domain: "ai-website-generator-tan.vercel.app",
    headline: "WebSeek.ai", headlineTail: "— AI website builder",
    role: "Solo · Design + Build",
    updated: "2026-07-28",
    stackLine: "React · Tailwind · Anthropic / OpenAI / Google",
    title: "WebSeek.ai — AI Website Builder · Divyansh Sood",
    description: "WebSeek.ai — our own bet on where agencies go next. One credit, one prompt, any language. Custom-coded output paired with Claude, GPT and Gemini.",
    ogTitle: "WebSeek.ai — AI website builder · Case study",
    ogDescription: "Our own bet on where agencies go next. One credit, one prompt, any language.",
    ogImage: "https://www.divyanshsood.com/images/work/webseek-1.webp",
    keywords: "AI website builder, AI website generator, prompt to website, Claude GPT Gemini website, custom-coded AI site, React Tailwind, Divyansh Sood",
    lead: `Our own bet on where agencies go next. One credit, one prompt, any language — paired with Claude, GPT or Gemini. Five free credits while we iterate.`,
    waHref: "https://wa.me/919816091875?text=Hi%20Divyansh,%20I%20want%20to%20build%20something%20like%20WebSeek.",
    feature: { src: "/images/work/webseek-1.webp", alt: "WebSeek.ai — the prompt bar and model picker on desktop" },
    metrics: [
      { v: "3", l: "Model providers running in production — Claude, GPT, Gemini" },
      { v: "1", l: "Prompt from blank page to deployed site" },
      { v: "Any", l: "Input language, without a separate flow" },
      { v: "HTML", l: "Output you own, not locked inside an editor" },
    ],
    outcome: "One prompt to a custom-coded site, with a Claude / GPT / Gemini model picker.",
    body: [
      { span2: true, tag: "The bet", title: "Custom output, not block-assembled templates", type: "prose",
        html: `Most "AI website builders" produce identical, sectioned-template marketing pages. We built the opposite: <em>custom-coded output</em>, plus a model picker — Claude for taste, GPT for breadth, Gemini for speed.` },
      { tag: "Audience", type: "list", oneCol: true,
        items: ["SMEs without a developer", "Designers wanting a draft fast", "Our own studio — dog food"] },
      { tag: "Stack", type: "list",
        items: ["React + Tailwind", "Anthropic SDK", "OpenAI SDK", "Google AI"] },
      { span2: true, tag: "The result", title: "Three providers in production, behind one prompt bar", type: "prose",
        html: `WebSeek runs <strong>Claude, GPT and Gemini side by side in a live product</strong>, not a demo — which means the differences between them are something I've had to handle in production: prompt shapes that work on one and not another, failure modes, cost and latency trade-offs. That experience is the reason AI features on client projects are reused code rather than an experiment billed to the client. The product is in active iteration and the output stays <em>ownable HTML</em>.` },
      { tag: "The lesson", type: "prose", oneCol: true,
        html: `Running your own product changes how you scope other people's. Every estimate I give now comes from having paid the cost of being wrong on something I owned.` },
    ],
    galleryLabel: "Gallery · 3 surfaces",
    gallery: [
      { src: "/images/work/webseek-1.webp", alt: "WebSeek.ai — prompt bar with the Claude, GPT and Gemini model picker" },
      { src: "/images/work/webseek-2.webp", alt: "WebSeek.ai — choosing a model before generating a site" },
      { src: "/images/work/webseek-3.webp", alt: "WebSeek.ai — generated site preview, ready to deploy" },
    ],
    // Mobile screenshots — drop phone-sized images into /public/images/work,
    // run scripts/gen-work-variants.mjs, and list them here to render a framed
    // "On mobile" gallery on this case study. Leave [] and nothing shows. Any
    // project below can use the same field, e.g.:
    //   mobileShots: [{ src: "/images/work/webseek-mobile-1.webp", alt: "… on a phone" }],
    mobileShots: [],
    faq: [
      { q: "What is WebSeek.ai?", a: "WebSeek.ai is an AI website generator built by Divyansh Sood Studio. You give it one prompt in any language and it returns a custom-coded website, with a model picker for Claude, GPT or Gemini." },
      { q: "Is WebSeek.ai free to try?", a: "Yes — every new user gets 5 free credits while the product is in active iteration. The output is ownable HTML, not locked inside a SaaS editor." },
      { q: "Which technologies power WebSeek.ai?", a: "React and Tailwind on the front end, with the Anthropic, OpenAI and Google AI SDKs powering the generation." },
    ],
    next: { slug: "baglamukhi-travels", name: "Baglamukhi Travels", label: "Next · 07" },
  },
  {
    slug: "baglamukhi-travels",
    num: "07", name: "Baglamukhi Travels", category: "Travel · Local SEO", year: "2026",
    liveUrl: "https://baglamukhitravels.com",
    domain: "baglamukhitravels.com",
    headline: "Baglamukhi Travels", headlineTail: "— Kangra taxi & Devi Darshan",
    role: "Solo · Design + Build",
    updated: "2026-07-28",
    stackLine: "Astro · JSON-LD · WhatsApp",
    title: "Baglamukhi Travels — Kangra Taxi Website · Divyansh Sood",
    description: "A family-run Kangra taxi operator up against commission agents and call centres. Custom-built with a full schema graph — now averaging position 5.7 on Google.",
    ogTitle: "Baglamukhi Travels — Kangra taxi & Devi Darshan · Case study",
    ogDescription: "Owner-driver taxi service in Kangra, built to win pilgrimage and airport-transfer search outright.",
    ogImage: "https://www.divyanshsood.com/images/work/baglamukhi-travels-1.webp",
    keywords: "Kangra taxi website, Devi Darshan yatra booking, Himachal cab service website, local SEO travel operator, Astro travel site, WhatsApp booking, schema markup local business, Divyansh Sood",
    lead: `Owner-drivers Kapil Dev and Sahil have run cabs out of Kangra since 2018 — but the bookings came through commission agents who owned the customer. The site had to win the searches that matter locally: Gaggal airport transfers, outstation runs, and the six-temple Devi Darshan yatra. It now averages position 5.7 on Google.`,
    waHref: "https://wa.me/919816091875?text=Hi%20Divyansh,%20I%20want%20a%20travel%20%2F%20taxi%20website.",
    feature: { src: "/images/work/baglamukhi-travels-1.webp", alt: "Baglamukhi Travels — Kangra taxi service homepage" },
    metrics: [
      { v: "5.7", l: "Avg. Google position, 28 days" },
      { v: "7.25K", l: "Search impressions, 28 days" },
      { v: "5.0★", l: "Google rating, 21 reviews" },
      { v: "6", l: "Temple Devi Darshan circuit" },
    ],
    outcome: "Averaging position 5.7 on Google — 7.25K impressions and 148 clicks in a 28-day window.",
    body: [
      { span2: true, tag: "The brief", title: "Cut out the agents, own the search", type: "prose",
        html: `Kangra's taxi trade runs on commission agents and call centres that sit between the traveller and the driver. Kapil and Sahil have been on the road since <strong>2018</strong> with a 5.0 Google rating and valid commercial permits — but no channel they controlled. The site had one job: be the thing that ranks, so the booking arrives directly.` },
      { tag: "Stack", type: "list", items: ["Astro", "Vercel", "JSON-LD graph", "WhatsApp deep-link", "llms.txt"] },
      { span2: true, tag: "What we shipped", title: "Ten pages, each aimed at a real search", type: "prose",
        html: `Dedicated pages for the intents people actually type — <strong>/devi-darshan</strong> for the six-temple yatra, <strong>/taxi-service</strong> for airport and railway transfers, plus packages, guides and FAQ. <strong>27 point-to-point routes</strong> are published with all-in fares, so the price is answered before anyone has to ask. Underneath sits a complete local-business schema graph: geo-coordinates, opening hours, an offer catalogue with real price specs, FAQ, and the aggregate rating. Booking is a one-tap WhatsApp deep-link to whichever owner is free — no advance, no agent.` },
      { span2: true, tag: "The result", title: "Position 5.7, from a standing start", type: "prose",
        html: `In a 28-day window the site drew <strong>7.25K impressions</strong> and <strong>148 clicks</strong> at an average position of <strong>5.7</strong> — first-page placement for a single-operator business competing against aggregators. An <code>llms.txt</code> file ships at the root so AI assistants can quote the routes and fares accurately too.` },
    ],
    galleryLabel: "Gallery · 2 surfaces",
    gallery: [
      { src: "/images/work/baglamukhi-travels-1.webp", alt: "Baglamukhi Travels — homepage hero" },
      { src: "/images/work/baglamukhi-travels-2.webp", alt: "Baglamukhi Travels — Devi Darshan yatra circuit" },
    ],
    faq: [
      { q: "What is Baglamukhi Travels?", a: "Baglamukhi Travels is a family-run taxi and tour operator in Kangra, Himachal Pradesh, run by owner-drivers Kapil Dev and Sahil since 2018. Divyansh Sood Studio built their website on Astro with a full local-business schema graph and WhatsApp booking." },
      { q: "How does the site perform in search?", a: "It averages position 5.7 on Google, drawing 7.25K impressions and 148 clicks in a 28-day window — first-page placement for a single-operator business competing against travel aggregators." },
      { q: "What stack does Baglamukhi Travels run on?", a: "Astro on Vercel, with a JSON-LD local-business graph, an llms.txt file for AI search, and one-tap WhatsApp deep-links instead of a booking gateway." },
    ],
    next: { slug: "northpeak", name: "North Peak Power Systems", label: "Next · 08" },
  },
  {
    slug: "dharamshala-tours",
    // Personal project — shown on /portfolio under "Personal projects", kept off the homepage deck.
    personal: true,
    num: "09", name: "Dharamshala Tours", category: "Travel · CMS", year: "2025",
    liveUrl: "https://dharamshalatours.in",
    domain: "dharamshalatours.in",
    headline: "Dharamshala Tours", headlineTail: "— WhatsApp-first travel",
    role: "Solo · Design + Build",
    updated: "2026-07-28",
    stackLine: "Astro · CMS · WhatsApp",
    title: "Dharamshala Tours — Travel Booking Site · Divyansh Sood",
    description: "Three school friends in Kangra, one WhatsApp-first booking flow. Skipped the accommodation-listing pattern. Part of ~1,000 packages booked monthly.",
    ogTitle: "Dharamshala Tours — Case study",
    ogDescription: "WhatsApp-first booking flow for a Kangra travel operator. ~1,000 packages a month.",
    ogImage: "https://www.divyanshsood.com/images/work/dharamshala-tours-1.webp",
    keywords: "Dharamshala tours, Kangra travel website, WhatsApp booking, travel packages Himachal, Astro CMS website, travel operator website India, Divyansh Sood",
    lead: `Three school friends in Kangra, one WhatsApp-first booking flow. We skipped the accommodation-listing pattern the competition uses — the site is part of ~1,000 travel packages booked every month.`,
    waHref: "https://wa.me/919816091875?text=Hi%20Divyansh,%20I%20want%20a%20travel%20website.",
    feature: { src: "/images/work/dharamshala-tours-1.webp", alt: "Dharamshala Tours — homepage hero on desktop" },
    metrics: [
      { v: "~1,000", l: "Packages booked through the site every month" },
      { v: "1-tap", l: "WhatsApp booking, package pre-filled" },
      { v: "Self-serve", l: "New itineraries published without a developer" },
      { v: "95%+", l: "Of traffic on phones — built mobile-first" },
    ],
    outcome: "Part of ~1,000 travel packages booked through the site every month.",
    body: [
      { span2: true, tag: "The brief", title: "Sell packages, not hotel listings", type: "prose",
        html: `Every Kangra travel operator runs the same template — a list of hotels with prices, a contact form nobody fills. The founders wanted to be different: they sell <em>packages</em>, not rooms, and most of conversion happens on WhatsApp.` },
      { tag: "Stack", type: "list", items: ["Astro", "WhatsApp deep-link", "Headless CMS", "Vercel"] },
      { span2: true, tag: "What we shipped", title: "Built around the WhatsApp moment", type: "prose",
        html: `Each package page ends in a <strong>one-tap WhatsApp deep link</strong> with the package pre-filled. The CMS lets the team push a new monsoon or winter itinerary without waiting on a developer. Mobile-first because 95%+ of their traffic is on phones.` },
      { span2: true, tag: "The result", title: "~1,000 packages a month, booked in a chat", type: "prose",
        html: `The site is part of roughly <strong>1,000 travel packages booked every month</strong>. It gets there by refusing the pattern every competitor copies: no hotel-listing grid, no contact form that goes nowhere. The booking ends where the customer already is — a WhatsApp thread with the package name already typed — and the team publishes seasonal itineraries themselves as demand shifts.` },
      { tag: "The lesson", type: "prose", oneCol: true,
        html: `Match the funnel to where the conversation actually happens. A form is not neutral — in this market it is a worse WhatsApp button.` },
    ],
    galleryLabel: "Gallery · 2 surfaces",
    gallery: [
      { src: "/images/work/dharamshala-tours-1.webp", alt: "Dharamshala Tours — homepage hero" },
      { src: "/images/work/dharamshala-tours-2.webp", alt: "Dharamshala Tours — seasonal guide" },
    ],
    faq: [
      { q: "What is Dharamshala Tours?", a: "Dharamshala Tours is a WhatsApp-first travel booking site for a Kangra operator run by three school friends, built by Divyansh Sood Studio. It sells travel packages rather than hotel listings." },
      { q: "How do customers book a trip?", a: "Every package page ends in a one-tap WhatsApp deep link with the package pre-filled, because most conversion happens on WhatsApp. The site is part of roughly 1,000 packages booked each month." },
      { q: "Can the team add new packages themselves?", a: "Yes — a headless CMS lets the team publish a new monsoon or winter itinerary without waiting on a developer." },
    ],
    next: { slug: "redline", name: "Redline Studios", label: "Back to · 01" },
  },
  {
    slug: "redline",
    num: "01", name: "Redline Studios", category: "Brand · E-commerce", year: "2025",
    liveUrl: "https://redlinestudios.in",
    domain: "redlinestudios.in",
    headline: "Redline Studios", headlineTail: "— apparel storefront",
    role: "Solo · Brand + Build",
    updated: "2026-07-28",
    stackLine: "Next.js · Razorpay · Custom storefront",
    title: "Redline Studios — Apparel Storefront · Divyansh Sood",
    description: "A motorcycle apparel brand born out of speed. F1 track-styled loaders, race-car geometry, hand-picked colours. Custom Next.js + Razorpay — nothing templated.",
    ogTitle: "Redline Studios — apparel storefront · Case study",
    ogDescription: "Motorcycle apparel brand born out of speed — F1-styled storefront, hand-built.",
    ogImage: "https://www.divyanshsood.com/images/work/redline-1.webp",
    keywords: "motorcycle apparel storefront, custom e-commerce India, Next.js storefront, Razorpay store, brand identity, F1 styled website, no Shopify, Divyansh Sood",
    lead: `A brand born out of speed. F1 track-styled loaders, race-car geometry, hand-picked racing colours. Nothing templated — every element hand-selected.`,
    waHref: "https://wa.me/919816091875?text=Hi%20Divyansh,%20I%20want%20a%20brand%20storefront.",
    feature: { src: "/images/work/redline-1.webp", alt: "Redline Studios — SS26 lookbook hero on desktop" },
    metrics: [
      { v: "1", l: "Sprint from blank page to live storefront" },
      { v: "3-in-1", l: "Brand identity, storefront and payments" },
      { v: "UPI · Card · COD", l: "Every way an Indian buyer wants to pay" },
      { v: "None", l: "Platform fees or theme licences, ever" },
    ],
    outcome: "Brand identity + storefront + payments, hand-built end-to-end in one sprint.",
    body: [
      { span2: true, tag: "The brief", title: "A storefront that feels like a track", type: "prose",
        html: `Not a Shopify theme dressed up in red and black. Something where every easing curve, loading state and product reveal carries the brand's <em>racing DNA</em>.` },
      { tag: "Founder, in 3 words", type: "quote",
        quote: `"Bhai bhai bhai! Ye kya banal cheez bana dia."`,
        // Gloss keeps the warmth of the original Hindi/Hinglish line for
        // Indian readers, while the English underneath makes the line
        // land for a US/UK prospect who doesn't read Devanagari.
        gloss: `"Bro bro bro! What a thing you've built."`,
        lang: "hi",
        attribution: "— Founder, Redline Studios" },
      { tag: "Stack", type: "list", items: ["Next.js", "Razorpay", "Custom motion", "Brand identity"] },
      { span2: true, tag: "What we shipped", title: "Brand + backend + frontend, one sprint", type: "prose",
        html: `A custom Next.js storefront with <strong>Razorpay</strong> (UPI, cards, COD), <strong>F1-inspired motion</strong> language, and a colour system pulled from actual racing liveries. Backend, frontend, design — one sprint.` },
      { span2: true, tag: "The result", title: "A brand that launched selling, not waiting", type: "prose",
        html: `Redline went from no identity and no storefront to <strong>live and taking payments in a single sprint</strong> — the logo, the motion language and the checkout all arriving together instead of a brand book sitting idle while a store gets built. Because it is custom code rather than a theme, there is no monthly platform fee and no licence to renew, and the next change to the buy flow does not need anyone's permission.` },
      { tag: "The lesson", type: "prose", oneCol: true,
        html: `When the brand and the storefront are made by the same person at the same time, the brand survives contact with the checkout. Split them and the identity gets flattened into whatever the theme allows.` },
    ],
    galleryLabel: "Gallery · 1 surface",
    gallery: [
      { src: "/images/work/redline-1.webp", alt: "Redline Studios — SS26 lookbook hero" },
    ],
    faq: [
      { q: "What is Redline Studios?", a: "Redline Studios is a motorcycle-apparel brand whose identity and storefront were built end-to-end by Divyansh Sood Studio — F1-styled motion, race-car geometry and a colour system pulled from real racing liveries." },
      { q: "Was the store built on Shopify?", a: "No. It is a custom Next.js storefront with zero Shopify themes, integrated with Razorpay for UPI, cards and cash on delivery." },
      { q: "How long did it take?", a: "Brand identity, backend, frontend and design were all delivered in a single sprint." },
    ],
    next: { slug: "cultxberserk", name: "CultXberserk", label: "Next · 02" },
  },
  {
    slug: "chinkiz",
    num: "03", name: "ChinkiZ Knitting Knife", category: "D2C · Creator", year: "2024",
    liveUrl: "https://chinkizknittingknife.com",
    domain: "chinkizknittingknife.com",
    headline: "ChinkiZ Knitting Knife", headlineTail: "— D2C storefront",
    role: "Solo · Design + Build",
    updated: "2026-07-28",
    stackLine: "Next.js · Razorpay · Custom video gallery",
    title: "ChinkiZ — Custom D2C Creator Storefront · Divyansh Sood",
    description: "Chinki runs a 600K+ YouTube channel. We built her a direct-to-consumer storefront in custom code — no Shopify — with a video gallery that matches her tutorials.",
    ogTitle: "ChinkiZ Knitting Knife — Case study",
    ogDescription: "A custom D2C storefront for a 600K-subscriber YouTuber. No Shopify, no theme — fully owned.",
    ogImage: "https://www.divyanshsood.com/images/work/chinkiz-1.webp",
    keywords: "creator storefront, YouTuber e-commerce, D2C website India, custom Next.js store, Razorpay storefront, video commerce, no Shopify, Divyansh Sood",
    lead: `Chinki runs a 600K+ YouTube channel. We built her a direct-to-consumer storefront in custom code — no Shopify, no theme marketplace — with a video gallery that matches the ritual of her tutorials.`,
    waHref: "https://wa.me/919816091875?text=Hi%20Divyansh,%20I%20want%20a%20creator%20storefront.",
    feature: { src: "/images/work/chinkiz-1.webp", alt: "ChinkiZ Knitting Knife — storefront hero on desktop" },
    metrics: [
      { v: "600K+", l: "Subscriber audience the storefront had to serve" },
      { v: "2 wks", l: "Brief to live, after two builders had failed" },
      { v: "Self-serve", l: "She adds a product the way she uploads a video" },
      { v: "None", l: "Platform fees or theme licences, ever" },
    ],
    outcome: "A custom-coded storefront with a native video gallery — full code ownership, no builder lock-in.",
    body: [
      { span2: true, tag: "The brief", title: "Where buy meets video", type: "prose",
        html: `Chinki tried two e-commerce builders. Both fought the way her audience shops — long tutorial videos, then a comment, then a DM. She wanted a site where the <em>video</em> sits next to the <em>buy button</em>, not buried under it.` },
      { tag: "In her words", type: "quote",
        quote: `"I did not think it could be achieved without going to e-commerce builders and only using custom code."`,
        attribution: "— Chinki, Founder" },
      { tag: "Stack", type: "list", items: ["Next.js", "Razorpay", "Custom video gallery", "Admin panel"] },
      { span2: true, tag: "What we shipped", title: "A storefront that feels like her tutorials", type: "prose",
        html: `A custom Next.js storefront with <strong>Razorpay</strong>, a <strong>video gallery</strong> mirroring her YouTube grid, and an <strong>admin panel</strong> where she adds products the way she'd add a video — title, thumbnail, done. Zero Shopify themes, zero builder lock-in, full code ownership.` },
      { span2: true, tag: "The result", title: "The store finally shops the way her audience does", type: "prose",
        html: `Two e-commerce builders had already failed at the same job, because both wanted the video to be a tab and the product to be a row in a grid. Here the demo sits beside the buy button, which is the actual sequence her viewers follow — watch, decide, buy. She publishes new products herself, <strong>in two weeks from brief to live</strong>, and owns the code outright.` },
      { tag: "The lesson", type: "prose", oneCol: true,
        html: `A creator's storefront is not a catalogue with videos added. It is the video, with a way to buy attached — and that ordering is exactly what off-the-shelf builders fight you on.` },
    ],
    galleryLabel: "Gallery · 2 surfaces",
    gallery: [
      { src: "/images/work/chinkiz-1.webp", alt: "ChinkiZ Knitting Knife — storefront hero" },
      { src: "/images/work/chinkiz-2.webp", alt: "ChinkiZ Knitting Knife — product collection grid" },
    ],
    faq: [
      { q: "What is ChinkiZ Knitting Knife?", a: "ChinkiZ Knitting Knife is a direct-to-consumer storefront built by Divyansh Sood Studio for Chinki, a creator with a 600K+ subscriber YouTube channel. The site puts her tutorial videos next to the buy button." },
      { q: "Does the store use Shopify or a website builder?", a: "No. It is fully custom-coded in Next.js with Razorpay payments — zero Shopify themes and zero builder lock-in, so the owner keeps full code ownership." },
      { q: "How does the owner add products?", a: "A custom admin panel lets her add a product the way she'd add a video — title, thumbnail, done — with a video gallery that mirrors her YouTube grid." },
    ],
    next: { slug: "nandini", name: "Nandini Travels", label: "Next · 04" },
  },
  {
    slug: "modernkbs",
    num: "05", name: "Modern K.B.S.", category: "Web App · Admin", year: "2024",
    liveUrl: "https://modernkbs.com",
    domain: "modernkbs.com",
    headline: "Modern K.B.S.", headlineTail: "— school site + admin panel",
    role: "Solo · Site + Admin Panel",
    updated: "2026-07-28",
    stackLine: "Next.js · Supabase · Admin dashboard",
    title: "Modern K.B.S. — School Site + Admin Panel · Divyansh Sood",
    description: "A senior secondary school in Ladwara. Website + application portal shipped together with a live admin panel. Quoted at 6 months elsewhere — delivered in 7 days.",
    ogTitle: "Modern K.B.S. — school portal · Case study",
    ogDescription: "School site + admissions admin panel — 6 months elsewhere, 7 days here.",
    ogImage: "https://www.divyanshsood.com/images/work/modernkbs-1.webp",
    keywords: "school website India, admissions portal, school admin panel, Next.js Supabase, education website developer, fast website delivery, Divyansh Sood",
    lead: `A senior secondary school in Ladwara. Website + application portal shipped together, live admin panel threaded through every surface. Other agencies quoted 6 months; we delivered in <em>7 days</em>.`,
    waHref: "https://wa.me/919816091875?text=Hi%20Divyansh,%20I%20want%20a%20school%20website%20with%20admin%20panel.",
    feature: { src: "/images/work/modernkbs-1.webp", alt: "Modern K.B.S. — homepage hero on desktop" },
    metrics: [
      { v: "7 days", l: "vs. 6 months quoted" },
      { v: "Site + Admin", l: "Same sprint" },
      { v: "I–XII", l: "Admissions live" },
      { v: "0 SaaS", l: "Recurring fees" },
    ],
    outcome: "Public site + admissions admin panel delivered in 7 days, where other agencies quoted 6 months.",
    body: [
      { span2: true, tag: "The brief", title: "Admissions before the academic cycle", type: "prose",
        html: `The school had been quoted six months and a recurring SaaS fee for an admissions portal. They needed it before the next cycle — measured in <em>weeks</em>, not quarters. And the office staff (not developers) had to run it.` },
      { tag: "In their words", type: "quote",
        quote: `"Every other agency said 6 months. Delivered in 7 days."`,
        attribution: "— Admin, Modern K.B.S., Ladwara" },
      { tag: "Stack", type: "list", items: ["Next.js", "Supabase", "Custom admin", "Razorpay (fees)"] },
      { span2: true, tag: "What we shipped", title: "Public site + admin panel, one sprint", type: "prose",
        html: `Faculty pages, fee structure, an enquiry-to-admission pipeline, and a <strong>dashboard the office uses daily</strong>. Zero learning curve — designed so any office staffer can update content without calling a developer.` },
      { span2: true, tag: "The result", title: "Live for the admissions cycle it was built for", type: "prose",
        html: `Seven days from brief to a working admissions portal, against <strong>six months quoted elsewhere</strong> — which mattered because the deadline was not a preference, it was the academic calendar. A six-month build would have missed the intake entirely and the school would have run another year on paper forms. Classes I–XII now apply through the site, the office processes them in the dashboard, and there is <strong>no recurring SaaS fee</strong> attached to any of it.` },
      { tag: "The lesson", type: "prose", oneCol: true,
        html: `Ask what the deadline is attached to. "Six months" is a reasonable estimate for a portal and a completely unreasonable one for a portal that has to exist before an intake — and scope, not speed, is what closes that gap.` },
    ],
    galleryLabel: "Gallery · 2 surfaces",
    gallery: [
      { src: "/images/work/modernkbs-1.webp", alt: "Modern K.B.S. — homepage hero" },
      { src: "/images/work/modernkbs-2.webp", alt: "Modern K.B.S. — notices and toppers" },
    ],
    faq: [
      { q: "What is Modern K.B.S.?", a: "Modern K.B.S. is a senior secondary school in Ladwara. Divyansh Sood Studio built its public website plus an admissions application portal and a live admin panel, all in one sprint." },
      { q: "How long did the build take?", a: "Seven days — where other agencies had quoted six months and a recurring SaaS fee." },
      { q: "Who runs the admin panel?", a: "Office staff, not developers. The dashboard was designed with zero learning curve so any staffer can update content and process admissions without calling a developer." },
    ],
    next: { slug: "webseek", name: "WebSeek.ai", label: "Next · 06" },
  },
  {
    slug: "nandini",
    num: "04", name: "Nandini Travels", category: "Travel · Local", year: "2025",
    liveUrl: "https://www.nandinitravel.com/",
    domain: "nandinitravel.com",
    headline: "Nandini Travels", headlineTail: "— Kangra taxi operator",
    role: "Solo · Design + Build",
    updated: "2026-07-28",
    stackLine: "Next.js · WhatsApp · Booking form",
    title: "Nandini Travels — Kangra Taxi Booking Site · Divyansh Sood",
    description: "Kangra's most-reviewed taxi operator had a broken site and zero direct bookings — all leads via Google Maps. Rebuilt in Next.js with on-site booking + WhatsApp.",
    ogTitle: "Nandini Travels — Kangra taxi operator · Case study",
    ogDescription: "Next.js rebuild for Kangra's most-reviewed taxi operator. Direct bookings now flow through the site instead of Google Maps.",
    ogImage: "https://www.divyanshsood.com/images/work/nandini-1.webp",
    keywords: "Kangra taxi website, taxi operator website India, travel booking form, WhatsApp booking, Next.js travel site, direct bookings, Google Maps alternative, Divyansh Sood",
    lead: `Kangra's most-positively-reviewed taxi operator was losing every lead to Google Maps. Their old site was down. We rebuilt it in Next.js with an on-site booking form, WhatsApp CTA, outstation packages and an airport-pickup option. Direct bookings now flow through the site.`,
    waHref: "https://wa.me/919816091875?text=Hi%20Divyansh,%20I%20want%20a%20travel%20%2F%20taxi%20website.",
    feature: { src: "/images/work/nandini-1.webp", alt: "Nandini Travels — Kangra taxi operator homepage hero" },
    // No "10x" tile here on purpose: that figure comes from the founder's own
    // words below and is a subjective impression, not a measurement. It reads
    // as data in a metric tile, so it stays in the quote where it belongs.
    metrics: [
      { v: "Direct", l: "Bookings through a funnel they own, not Google Maps" },
      { v: "Live", l: "Rebuilt from a site that was down entirely" },
      { v: "1-tap", l: "WhatsApp booking on every package" },
      { v: "N. India", l: "Outstation routes covered" },
    ],
    outcome: "Direct bookings now flow through a site the operator owns, instead of leaking to Google Maps.",
    body: [
      { span2: true, tag: "The brief", title: "Best reviews in Kangra. Worst funnel.", type: "prose",
        html: `Nandini Travels has the strongest review profile of any taxi operator in Kangra — but every booking arrived through Google Maps, and the old website was down. There was no funnel they owned. Margins shrank with every Maps-driven enquiry.` },
      { tag: "In their words", type: "quote",
        quote: `"The website is so beautiful — looks 10 times more premium than our competitors. We started getting direct bookings instead of losing them to Google Maps."`,
        attribution: "— Founder, Nandini Travels" },
      { tag: "Stack", type: "list", items: ["Next.js", "WhatsApp deep-link", "Booking form", "Vercel"] },
      { span2: true, tag: "What we shipped", title: "A funnel they own — built around the WhatsApp moment", type: "prose",
        html: `A Next.js rebuild with an <strong>on-site booking form</strong>, a one-tap WhatsApp CTA on every package, outstation routes across North Indian states, and an airport-pickup flow. Faster than the old site. Mobile-first because almost every booking starts on a phone.` },
      { span2: true, tag: "The result", title: "The best reviews in Kangra finally have somewhere to land", type: "prose",
        html: `Enquiries now arrive on a site the operator controls instead of a Maps listing that could be reordered by Google at any time. The strongest review profile in the district was previously feeding a channel someone else owned — the rebuild turned it into <strong>direct bookings against their own brand</strong>. The founder's read on the change is in their words above; it's an impression rather than a measurement, and it's presented that way.` },
      { tag: "The lesson", type: "prose", oneCol: true,
        html: `Great reviews are not a funnel. If the only place they exist is a platform's listing, the platform decides who sees them — and takes the relationship with the customer.` },
    ],
    galleryLabel: "Gallery · 2 surfaces",
    gallery: [
      { src: "/images/work/nandini-1.webp", alt: "Nandini Travels — homepage hero" },
      { src: "/images/work/nandini-2.webp", alt: "Nandini Travels — authorised-operator credentials" },
    ],
    faq: [
      { q: "What is Nandini Travels?", a: "Nandini Travels is Kangra's most-positively-reviewed taxi operator. Divyansh Sood Studio rebuilt their website in Next.js with an on-site booking form, a WhatsApp CTA, outstation packages and airport pickup." },
      { q: "Why did the site need rebuilding?", a: "Every booking used to arrive through Google Maps and the old site was down, so the operator owned no funnel. After the rebuild, direct bookings now flow through the site." },
      { q: "What did the founder say about the result?", a: "“The website is so beautiful — looks 10 times more premium than our competitors. We started getting direct bookings instead of losing them to Google Maps.”" },
    ],
    next: { slug: "modernkbs", name: "Modern K.B.S.", label: "Next · 05" },
  },
  {
    slug: "northpeak",
    // Personal project — shown on /portfolio under "Personal projects", kept off the homepage deck.
    personal: true,
    num: "08", name: "North Peak Power Systems", category: "Infra · Dashboard", year: "2025",
    liveUrl: "https://northpeakpowersystems.vercel.app/",
    domain: "northpeakpowersystems.vercel.app",
    headline: "North Peak Power Systems", headlineTail: "— solar contractor portal",
    role: "Solo · Site + Dashboard",
    updated: "2026-07-28",
    stackLine: "Angular · Project gallery · Admin",
    title: "North Peak — Solar Contractor Website · Divyansh Sood",
    description: "Himachal electrical & solar contractor breaking into the private sector. 15-page Angular site with project gallery, work calendar and self-serve admin.",
    ogTitle: "North Peak Power Systems — solar contractor portal · Case study",
    ogDescription: "15-page Angular site + dashboard-cum-admin for a Himachal electrical/solar contractor breaking into the private sector.",
    ogImage: "https://www.divyanshsood.com/images/work/northpeak-1.webp",
    keywords: "solar contractor website, electrical contractor portal, Angular website, project gallery, admin dashboard, Himachal solar, government to private, Divyansh Sood",
    lead: `Himachal electrical &amp; solar contractor doing mostly government work, breaking into the private sector dominated by digital + offline competitors. We shipped a 15-page Angular site, a project gallery, a work calendar and a dashboard-cum-admin — they publish new project case studies themselves.`,
    waHref: "https://wa.me/919816091875?text=Hi%20Divyansh,%20I%20want%20a%20site%20%2B%20admin%20panel%20for%20my%20business.",
    feature: { src: "/images/work/northpeak-1.webp", alt: "North Peak Power Systems — homepage hero on desktop" },
    metrics: [
      { v: "15", l: "Pages shipped, every one editable by the team" },
      { v: "Self-serve", l: "New projects published without a developer" },
      { v: "Govt → Pvt", l: "A private-sector pitch they can lead with" },
      { v: "0", l: "Developer tickets to change a headline" },
    ],
    outcome: "A 15-page portal + self-serve admin that finally lets the team lead with a private-sector pitch.",
    body: [
      { span2: true, tag: "The brief", title: "Govt → private. With proof, not promises.", type: "prose",
        html: `The team was excellent at government tenders but invisible in the private market — where buyers want photos, recent projects and a clear pitch. The site had to <em>showcase work</em> credibly and let the team add new case studies themselves, not via a developer.` },
      { tag: "In their words", type: "quote",
        quote: `"Divyansh, exactly yahi chahiye tha. Humne pehle jisse karwaya tha vo sirf photos laga ke chala gaya. Mein apne circle mein lifetime zaroor refer karunga."`,
        attribution: "— Founder, North Peak Power Systems" },
      { tag: "Stack", type: "list", items: ["Angular", "Project gallery", "Work calendar", "Custom admin"] },
      { span2: true, tag: "What we shipped", title: "15 pages + a dashboard the team actually uses", type: "prose",
        html: `Service pages for solar, electrical and infra. A <strong>project gallery</strong> they update without dev help. A work calendar so prospects can see active engagements. A <strong>dashboard-cum-admin</strong> for new uploads — designed for a non-technical operator.` },
      { span2: true, tag: "The result", title: "Proof that keeps accumulating without me", type: "prose",
        html: `Private-sector buyers judge a contractor on recent, visible work — exactly what a government-tender track record fails to show. The team now <strong>publishes each completed job themselves</strong>, so the portfolio grows every month instead of ageing until someone budgets for a website refresh. Their last developer, in the founder's words above, "just put up photos and left"; the difference here is that the site is theirs to run.` },
      { tag: "The lesson", type: "prose", oneCol: true,
        html: `For a proof-driven business, the admin panel <em>is</em> the deliverable. A beautiful site nobody can update is a brochure with a hosting bill.` },
    ],
    galleryLabel: "Gallery · 2 surfaces",
    gallery: [
      { src: "/images/work/northpeak-1.webp", alt: "North Peak Power Systems — homepage hero" },
      { src: "/images/work/northpeak-2.webp", alt: "North Peak Power Systems — services overview" },
    ],
    faq: [
      { q: "What is North Peak Power Systems?", a: "North Peak Power Systems is a Himachal electrical and solar contractor. Divyansh Sood Studio built a 15-page Angular site with a project gallery, work calendar and a dashboard-cum-admin to help them break into the private sector." },
      { q: "Can the team publish new projects without a developer?", a: "Yes — a dashboard-cum-admin, designed for a non-technical operator, lets the team upload new project case studies and update the gallery themselves." },
      { q: "What framework was used?", a: "Angular, across all 15 pages, with a custom admin dashboard." },
    ],
    next: { slug: "dharamshala-tours", name: "Dharamshala Tours", label: "Next · 09" },
  },
  {
    slug: "cultxberserk",
    num: "02", name: "CultXberserk", category: "Brand · D2C", year: "2026",
    liveUrl: "https://cultxberserk.com",
    domain: "cultxberserk.com",
    headline: "CultXberserk", headlineTail: "— Berserk-inspired apparel",
    role: "Solo · Brand + Build",
    updated: "2026-07-28",
    stackLine: "Next.js · ImageKit · Custom storefront",
    title: "CultXberserk — Anime Apparel Brand Store · Divyansh Sood",
    description: "A gothic apparel label built around the world of Berserk. Hand-numbered drops (0001–0666), 13 designs never reprinted. Custom-coded — no Shopify theme.",
    ogTitle: "CultXberserk — Berserk-inspired apparel · Case study",
    ogDescription: "A lore-driven apparel brand with hand-numbered drops and a custom-coded storefront. No Shopify theme.",
    ogImage: "https://www.divyanshsood.com/images/work/cultxberserk-1.webp",
    keywords: "Berserk apparel, gothic streetwear brand, hand-numbered drops, custom e-commerce India, Next.js storefront, anime apparel, D2C clothing brand, no Shopify, Divyansh Sood",
    lead: `A gothic apparel label built around the world of Berserk. Heavyweight, garment-dyed tees that are hand-numbered (0001–0666) and never reprinted — each carrying a "Brand of Sacrifice" seal at the neckline. The storefront is custom-coded, so the lore and the buy flow are one experience.`,
    waHref: "https://wa.me/919816091875?text=Hi%20Divyansh,%20I%20want%20a%20brand%20storefront.",
    feature: { src: "/images/work/cultxberserk-1.webp", alt: "CultXberserk — lore-driven storefront hero on desktop" },
    metrics: [
      { v: "0001–0666", l: "Units the storefront numbers and retires on its own" },
      { v: "13", l: "Designs, never reprinted — enforced in code, not a spreadsheet" },
      { v: "3", l: "Lore surfaces built beside the buy flow" },
      { v: "None", l: "Platform fees or theme licences, ever" },
    ],
    outcome: "A custom-coded storefront where the lore, the drop mechanics and the buy flow are one experience — not a dressed-up theme.",
    body: [
      { span2: true, tag: "The bet", title: "Lore-driven commerce, not a merch store", type: "prose",
        html: `Most anime-adjacent labels print a graphic and ship it on a generic store. CultXberserk is the opposite: a brand with its own canon — Japanese lettering, Roman numerals, a <em>"Brand of Sacrifice"</em> seal at the C7 vertebra — where the storytelling and the storefront are built as one thing.` },
      { tag: "Brand voice", type: "quote",
        quote: `"Apparel for the damned."` },
      { tag: "Stack", type: "list", items: ["Next.js", "ImageKit", "Custom cart", "Drop mechanics"] },
      { span2: true, tag: "What we shipped", title: "A storefront that reads like the manga", type: "prose",
        html: `A custom Next.js storefront with <strong>ImageKit</strong>-optimised product imagery, a <strong>hand-numbered drop system</strong> (0001–0666, never reprinted), and dedicated <em>Lore</em>, <em>Drops</em> and <em>Council</em> surfaces so the world-building lives next to the buy button. Zero Shopify themes — full code ownership, end to end.` },
      { span2: true, tag: "The result", title: "Scarcity the system enforces, not the founder", type: "prose",
        html: `The drop mechanic is <strong>part of the software</strong>: numbers are issued in sequence, a design retires when its run is done, and nothing has to be manually pulled or tracked in a sheet. That matters for a brand whose entire promise is that a piece is never reprinted — the claim is only as good as the thing enforcing it. No app store sells this mechanic, which is the reason it is coded rather than configured.` },
      { tag: "The lesson", type: "prose", oneCol: true,
        html: `If your brand's promise is a mechanic, the mechanic has to live in the product. Anything a founder has to remember to do by hand is a promise waiting to break on a busy launch day.` },
    ],
    galleryLabel: "Gallery · 2 surfaces",
    gallery: [
      { src: "/images/work/cultxberserk-1.webp", alt: "CultXberserk — lore-driven storefront hero" },
      { src: "/images/work/cultxberserk-2.webp", alt: "CultXberserk — brand lore section" },
    ],
    faq: [
      { q: "What is CultXberserk?", a: "CultXberserk is a gothic apparel brand inspired by Kentaro Miura's manga Berserk, with a custom-coded storefront built by Divyansh Sood Studio. It sells heavyweight, garment-dyed tees that are hand-numbered and never reprinted." },
      { q: "Was the store built on Shopify?", a: "No. It is a custom Next.js storefront with ImageKit-optimised imagery and a bespoke drop system — zero Shopify themes, so the brand keeps full code ownership." },
      { q: "What makes the drops exclusive?", a: "Every garment is hand-numbered from 0001 to 0666 across 13 designs and is never reprinted, and each carries a 'Brand of Sacrifice' seal sewn into the neckline at the C7 vertebra." },
    ],
    next: { slug: "chinkiz", name: "ChinkiZ Knitting Knife", label: "Next · 03" },
  },
];
