/* ===========================================================================
   Project case-study data (content only). Pure data — no rendering logic.
   The HTML renderer + JSON-LD live in ./render.mjs.
   =========================================================================== */

export { SITE } from "../site.mjs";

export const projects = [
  {
    slug: "webseek",
    num: "06", name: "WebSeek.ai", category: "AI Product", year: "2026",
    liveUrl: "https://ai-website-generator-tan.vercel.app",
    domain: "ai-website-generator-tan.vercel.app",
    headline: "WebSeek.ai", headlineTail: "— AI website builder",
    role: "Solo · Design + Build",
    stackLine: "React · Tailwind · Anthropic / OpenAI / Google",
    title: "WebSeek.ai — AI website builder · Case study · Divyansh Sood",
    description: "WebSeek.ai — our own bet on where agencies go next. One credit, one prompt, any language. Custom-coded output paired with Claude, GPT and Gemini.",
    ogTitle: "WebSeek.ai — AI website builder · Case study",
    ogDescription: "Our own bet on where agencies go next. One credit, one prompt, any language.",
    ogImage: "https://ik.imagekit.io/dn2zdxiu3/Portfolioprojectimages/AiWebsitegenerator/AiWebsitegenerator-1.webp",
    keywords: "AI website builder, AI website generator, prompt to website, Claude GPT Gemini website, custom-coded AI site, React Tailwind, Divyansh Sood",
    lead: `Our own bet on where agencies go next. One credit, one prompt, any language — paired with Claude, GPT or Gemini. Five free credits while we iterate.`,
    waHref: "https://wa.me/919816091875?text=Hi%20Divyansh,%20I%20want%20to%20build%20something%20like%20WebSeek.",
    feature: { src: "https://ik.imagekit.io/dn2zdxiu3/Portfolioprojectimages/AiWebsitegenerator/AiWebsitegenerator-1.webp", alt: "WebSeek.ai — primary product surface" },
    metrics: [
      { v: "3", l: "AI models, one app" },
      { v: "5", l: "Free credits" },
      { v: "1", l: "Prompt → site" },
      { v: "Any", l: "Language input" },
    ],
    outcome: "One prompt to a custom-coded site, with a Claude / GPT / Gemini model picker.",
    body: [
      { span2: true, tag: "The bet", title: "Custom output, not block-assembled templates", type: "prose",
        html: `Most "AI website builders" produce identical, sectioned-template marketing pages. We built the opposite: <em>custom-coded output</em>, plus a model picker — Claude for taste, GPT for breadth, Gemini for speed.` },
      { tag: "Audience", type: "list", oneCol: true,
        items: ["SMEs without a developer", "Designers wanting a draft fast", "Our own studio — dog food"] },
      { tag: "Stack", type: "list",
        items: ["React + Tailwind", "Anthropic SDK", "OpenAI SDK", "Google AI"] },
      { span2: true, tag: "Status", title: "In active build · 5 free credits live", type: "prose",
        html: `The product is in active iteration. <strong>5 free credits</strong> for early users while we tune output quality. The output is <em>ownable HTML</em> — not stuck in a SaaS editor.` },
    ],
    galleryLabel: "Gallery · 3 surfaces",
    gallery: [
      { src: "https://ik.imagekit.io/dn2zdxiu3/Portfolioprojectimages/AiWebsitegenerator/AiWebsitegenerator-1.webp", alt: "WebSeek.ai — generator surface" },
      { src: "https://ik.imagekit.io/dn2zdxiu3/Portfolioprojectimages/AiWebsitegenerator/AiWebsitegenerator-2.webp", alt: "WebSeek.ai — model picker" },
      { src: "https://ik.imagekit.io/dn2zdxiu3/Portfolioprojectimages/AiWebsitegenerator/AiWebsitegenerator-3.webp", alt: "WebSeek.ai — output preview" },
    ],
    // Mobile screenshots — paste phone-sized image URLs here and a framed "On
    // mobile" gallery renders on this case study. Leave [] and nothing shows.
    // Any project below can use the same field, e.g.:
    //   mobileShots: [{ src: "https://ik.imagekit.io/.../mobile-1.webp", alt: "… on a phone" }],
    mobileShots: [],
    faq: [
      { q: "What is WebSeek.ai?", a: "WebSeek.ai is an AI website generator built by Divyansh Sood Studio. You give it one prompt in any language and it returns a custom-coded website, with a model picker for Claude, GPT or Gemini." },
      { q: "Is WebSeek.ai free to try?", a: "Yes — every new user gets 5 free credits while the product is in active iteration. The output is ownable HTML, not locked inside a SaaS editor." },
      { q: "Which technologies power WebSeek.ai?", a: "React and Tailwind on the front end, with the Anthropic, OpenAI and Google AI SDKs powering the generation." },
    ],
    next: { slug: "baglamukhi-travels", name: "Baglamukhi Travels", label: "Next · 07" },
  },
  {
    slug: "baglamukhi-travels",
    num: "07", name: "Baglamukhi Travels", category: "Travel · Local SEO", year: "2026",
    liveUrl: "https://baglamukhitravels.com",
    domain: "baglamukhitravels.com",
    headline: "Baglamukhi Travels", headlineTail: "— Kangra taxi & Devi Darshan",
    role: "Solo · Design + Build",
    stackLine: "Astro · JSON-LD · WhatsApp",
    title: "Baglamukhi Travels — Kangra taxi & Devi Darshan · Case study · Divyansh Sood",
    description: "A family-run Kangra taxi operator competing with commission agents and call centres. Built on Astro with a full local-business schema graph — now averaging position 5.7 on Google.",
    ogTitle: "Baglamukhi Travels — Kangra taxi & Devi Darshan · Case study",
    ogDescription: "Owner-driver taxi service in Kangra, built to win pilgrimage and airport-transfer search outright.",
    ogImage: "https://www.divyanshsood.com/images/work/baglamukhi-travels-1.webp",
    keywords: "Kangra taxi website, Devi Darshan yatra booking, Himachal cab service website, local SEO travel operator, Astro travel site, WhatsApp booking, schema markup local business, Divyansh Sood",
    lead: `Owner-drivers Kapil Dev and Sahil have run cabs out of Kangra since 2018 — but the bookings came through commission agents who owned the customer. The site had to win the searches that matter locally: Gaggal airport transfers, outstation runs, and the six-temple Devi Darshan yatra. It now averages position 5.7 on Google.`,
    waHref: "https://wa.me/919816091875?text=Hi%20Divyansh,%20I%20want%20a%20travel%20%2F%20taxi%20website.",
    feature: { src: "/images/work/baglamukhi-travels-1.webp", alt: "Baglamukhi Travels — Kangra taxi service homepage" },
    metrics: [
      { v: "5.7", l: "Avg. Google position, 28 days" },
      { v: "7.25K", l: "Search impressions, 28 days" },
      { v: "5.0★", l: "Google rating, 21 reviews" },
      { v: "6", l: "Temple Devi Darshan circuit" },
    ],
    outcome: "Averaging position 5.7 on Google — 7.25K impressions and 148 clicks in a 28-day window.",
    body: [
      { span2: true, tag: "The brief", title: "Cut out the agents, own the search", type: "prose",
        html: `Kangra's taxi trade runs on commission agents and call centres that sit between the traveller and the driver. Kapil and Sahil have been on the road since <strong>2018</strong> with a 5.0 Google rating and valid commercial permits — but no channel they controlled. The site had one job: be the thing that ranks, so the booking arrives directly.` },
      { tag: "Stack", type: "list", items: ["Astro", "Vercel", "JSON-LD graph", "WhatsApp deep-link", "llms.txt"] },
      { span2: true, tag: "What we shipped", title: "Ten pages, each aimed at a real search", type: "prose",
        html: `Dedicated pages for the intents people actually type — <strong>/devi-darshan</strong> for the six-temple yatra, <strong>/taxi-service</strong> for airport and railway transfers, plus packages, guides and FAQ. <strong>27 point-to-point routes</strong> are published with all-in fares, so the price is answered before anyone has to ask. Underneath sits a complete local-business schema graph: geo-coordinates, opening hours, an offer catalogue with real price specs, FAQ, and the aggregate rating. Booking is a one-tap WhatsApp deep-link to whichever owner is free — no advance, no agent.` },
      { span2: true, tag: "The result", title: "Position 5.7, from a standing start", type: "prose",
        html: `In a 28-day window the site drew <strong>7.25K impressions</strong> and <strong>148 clicks</strong> at an average position of <strong>5.7</strong> — first-page placement for a single-operator business competing against aggregators. An <code>llms.txt</code> file ships at the root so AI assistants can quote the routes and fares accurately too.` },
    ],
    galleryLabel: "Gallery · 2 surfaces",
    gallery: [
      { src: "/images/work/baglamukhi-travels-1.webp", alt: "Baglamukhi Travels — homepage hero" },
      { src: "/images/work/baglamukhi-travels-2.webp", alt: "Baglamukhi Travels — Devi Darshan yatra circuit" },
    ],
    faq: [
      { q: "What is Baglamukhi Travels?", a: "Baglamukhi Travels is a family-run taxi and tour operator in Kangra, Himachal Pradesh, run by owner-drivers Kapil Dev and Sahil since 2018. Divyansh Sood Studio built their website on Astro with a full local-business schema graph and WhatsApp booking." },
      { q: "How does the site perform in search?", a: "It averages position 5.7 on Google, drawing 7.25K impressions and 148 clicks in a 28-day window — first-page placement for a single-operator business competing against travel aggregators." },
      { q: "What stack does Baglamukhi Travels run on?", a: "Astro on Vercel, with a JSON-LD local-business graph, an llms.txt file for AI search, and one-tap WhatsApp deep-links instead of a booking gateway." },
    ],
    next: { slug: "northpeak", name: "North Peak Power Systems", label: "Next · 08" },
  },
  {
    slug: "dharamshala-tours",
    // Personal project — shown on /portfolio under "Personal projects", kept off the homepage deck.
    personal: true,
    num: "09", name: "Dharamshala Tours", category: "Travel · CMS", year: "2025",
    liveUrl: "https://dharamshalatours.in",
    domain: "dharamshalatours.in",
    headline: "Dharamshala Tours", headlineTail: "— WhatsApp-first travel",
    role: "Solo · Design + Build",
    stackLine: "Astro · CMS · WhatsApp",
    title: "Dharamshala Tours — WhatsApp-first travel · Case study · Divyansh Sood",
    description: "Three school friends in Kangra, one WhatsApp-first booking flow. Skipped the accommodation-listing pattern. Part of ~1,000 packages booked monthly.",
    ogTitle: "Dharamshala Tours — Case study",
    ogDescription: "WhatsApp-first booking flow for a Kangra travel operator. ~1,000 packages a month.",
    ogImage: "https://www.divyanshsood.com/images/work/dharamshala-tours-1.webp",
    keywords: "Dharamshala tours, Kangra travel website, WhatsApp booking, travel packages Himachal, Astro CMS website, travel operator website India, Divyansh Sood",
    lead: `Three school friends in Kangra, one WhatsApp-first booking flow. We skipped the accommodation-listing pattern the competition uses — the site is part of ~1,000 travel packages booked every month.`,
    waHref: "https://wa.me/919816091875?text=Hi%20Divyansh,%20I%20want%20a%20travel%20website.",
    feature: { src: "/images/work/dharamshala-tours-1.webp", alt: "Dharamshala Tours — homepage hero on desktop" },
    metrics: [
      { v: "~1,000", l: "Bookings / month" },
      { v: "1-tap", l: "WhatsApp deep-link" },
      { v: "3", l: "Founders, Kangra" },
      { v: "CMS", l: "Self-serve editor" },
    ],
    outcome: "Part of ~1,000 travel packages booked through the site every month.",
    body: [
      { span2: true, tag: "The brief", title: "Sell packages, not hotel listings", type: "prose",
        html: `Every Kangra travel operator runs the same template — a list of hotels with prices, a contact form nobody fills. The founders wanted to be different: they sell <em>packages</em>, not rooms, and most of conversion happens on WhatsApp.` },
      { tag: "The result", type: "quote",
        quote: `~1,000 packages booked through the site every month.` },
      { tag: "Stack", type: "list", items: ["Astro", "WhatsApp deep-link", "Headless CMS", "Vercel"] },
      { span2: true, tag: "What we shipped", title: "Built around the WhatsApp moment", type: "prose",
        html: `Each package page ends in a <strong>one-tap WhatsApp deep link</strong> with the package pre-filled. The CMS lets the team push a new monsoon or winter itinerary without waiting on a developer. Mobile-first because 95%+ of their traffic is on phones.` },
    ],
    galleryLabel: "Gallery · 2 surfaces",
    gallery: [
      { src: "/images/work/dharamshala-tours-1.webp", alt: "Dharamshala Tours — homepage hero" },
      { src: "/images/work/dharamshala-tours-2.webp", alt: "Dharamshala Tours — seasonal guide" },
    ],
    faq: [
      { q: "What is Dharamshala Tours?", a: "Dharamshala Tours is a WhatsApp-first travel booking site for a Kangra operator run by three school friends, built by Divyansh Sood Studio. It sells travel packages rather than hotel listings." },
      { q: "How do customers book a trip?", a: "Every package page ends in a one-tap WhatsApp deep link with the package pre-filled, because most conversion happens on WhatsApp. The site is part of roughly 1,000 packages booked each month." },
      { q: "Can the team add new packages themselves?", a: "Yes — a headless CMS lets the team publish a new monsoon or winter itinerary without waiting on a developer." },
    ],
    next: { slug: "redline", name: "Redline Studios", label: "Back to · 01" },
  },
  {
    slug: "redline",
    num: "01", name: "Redline Studios", category: "Brand · E-commerce", year: "2025",
    liveUrl: "https://redlinestudios.in",
    domain: "redlinestudios.in",
    headline: "Redline Studios", headlineTail: "— apparel storefront",
    role: "Solo · Brand + Build",
    stackLine: "Next.js · Razorpay · Custom storefront",
    title: "Redline Studios — apparel brand storefront · Divyansh Sood",
    description: "A motorcycle apparel brand born out of speed. F1 track-styled loaders, race-car geometry, hand-picked colours. Custom Next.js + Razorpay — nothing templated.",
    ogTitle: "Redline Studios — apparel storefront · Case study",
    ogDescription: "Motorcycle apparel brand born out of speed — F1-styled storefront, hand-built.",
    ogImage: "https://www.divyanshsood.com/images/work/redline-1.webp",
    keywords: "motorcycle apparel storefront, custom e-commerce India, Next.js storefront, Razorpay store, brand identity, F1 styled website, no Shopify, Divyansh Sood",
    lead: `A brand born out of speed. F1 track-styled loaders, race-car geometry, hand-picked racing colours. Nothing templated — every element hand-selected.`,
    waHref: "https://wa.me/919816091875?text=Hi%20Divyansh,%20I%20want%20a%20brand%20storefront.",
    feature: { src: "/images/work/redline-1.webp", alt: "Redline Studios — SS26 lookbook hero on desktop" },
    metrics: [
      { v: "1", l: "Sprint, end-to-end" },
      { v: "Brand", l: "From scratch" },
      { v: "Razorpay", l: "UPI · Card · COD" },
      { v: "0", l: "Shopify themes" },
    ],
    outcome: "Brand identity + storefront + payments, hand-built end-to-end in one sprint.",
    body: [
      { span2: true, tag: "The brief", title: "A storefront that feels like a track", type: "prose",
        html: `Not a Shopify theme dressed up in red and black. Something where every easing curve, loading state and product reveal carries the brand's <em>racing DNA</em>.` },
      { tag: "Founder, in 3 words", type: "quote",
        quote: `"Bhai bhai bhai! Ye kya banal cheez bana dia."`,
        // Gloss keeps the warmth of the original Hindi/Hinglish line for
        // Indian readers, while the English underneath makes the line
        // land for a US/UK prospect who doesn't read Devanagari.
        gloss: `"Bro bro bro! What a thing you've built."`,
        lang: "hi",
        attribution: "— Founder, Redline Studios" },
      { tag: "Stack", type: "list", items: ["Next.js", "Razorpay", "Custom motion", "Brand identity"] },
      { span2: true, tag: "What we shipped", title: "Brand + backend + frontend, one sprint", type: "prose",
        html: `A custom Next.js storefront with <strong>Razorpay</strong> (UPI, cards, COD), <strong>F1-inspired motion</strong> language, and a colour system pulled from actual racing liveries. Backend, frontend, design — one sprint.` },
    ],
    galleryLabel: "Gallery · 1 surface",
    gallery: [
      { src: "/images/work/redline-1.webp", alt: "Redline Studios — SS26 lookbook hero" },
    ],
    faq: [
      { q: "What is Redline Studios?", a: "Redline Studios is a motorcycle-apparel brand whose identity and storefront were built end-to-end by Divyansh Sood Studio — F1-styled motion, race-car geometry and a colour system pulled from real racing liveries." },
      { q: "Was the store built on Shopify?", a: "No. It is a custom Next.js storefront with zero Shopify themes, integrated with Razorpay for UPI, cards and cash on delivery." },
      { q: "How long did it take?", a: "Brand identity, backend, frontend and design were all delivered in a single sprint." },
    ],
    next: { slug: "cultxberserk", name: "CultXberserk", label: "Next · 02" },
  },
  {
    slug: "chinkiz",
    num: "03", name: "ChinkiZ Knitting Knife", category: "D2C · Creator", year: "2024",
    liveUrl: "https://chinkizknittingknife.com",
    domain: "chinkizknittingknife.com",
    headline: "ChinkiZ Knitting Knife", headlineTail: "— D2C storefront",
    role: "Solo · Design + Build",
    stackLine: "Next.js · Razorpay · Custom video gallery",
    title: "ChinkiZ Knitting Knife — D2C storefront · Case study · Divyansh Sood",
    description: "Chinki runs a 600K+ YouTube channel. We built her a direct-to-consumer storefront in custom code — no Shopify — with a video gallery that matches her tutorials.",
    ogTitle: "ChinkiZ Knitting Knife — Case study",
    ogDescription: "A custom D2C storefront for a 600K-subscriber YouTuber. No Shopify, no theme — fully owned.",
    ogImage: "https://www.divyanshsood.com/images/work/chinkiz-1.webp",
    keywords: "creator storefront, YouTuber e-commerce, D2C website India, custom Next.js store, Razorpay storefront, video commerce, no Shopify, Divyansh Sood",
    lead: `Chinki runs a 600K+ YouTube channel. We built her a direct-to-consumer storefront in custom code — no Shopify, no theme marketplace — with a video gallery that matches the ritual of her tutorials.`,
    waHref: "https://wa.me/919816091875?text=Hi%20Divyansh,%20I%20want%20a%20creator%20storefront.",
    feature: { src: "/images/work/chinkiz-1.webp", alt: "ChinkiZ Knitting Knife — storefront hero on desktop" },
    metrics: [
      { v: "600K+", l: "YouTube subscribers" },
      { v: "0", l: "Themes used" },
      { v: "Razorpay", l: "UPI · Card · COD" },
      { v: "2 wks", l: "Brief to live" },
    ],
    outcome: "A custom-coded storefront with a native video gallery — full code ownership, no builder lock-in.",
    body: [
      { span2: true, tag: "The brief", title: "Where buy meets video", type: "prose",
        html: `Chinki tried two e-commerce builders. Both fought the way her audience shops — long tutorial videos, then a comment, then a DM. She wanted a site where the <em>video</em> sits next to the <em>buy button</em>, not buried under it.` },
      { tag: "In her words", type: "quote",
        quote: `"I did not think it could be achieved without going to e-commerce builders and only using custom code."`,
        attribution: "— Chinki, Founder" },
      { tag: "Stack", type: "list", items: ["Next.js", "Razorpay", "Custom video gallery", "Admin panel"] },
      { span2: true, tag: "What we shipped", title: "A storefront that feels like her tutorials", type: "prose",
        html: `A custom Next.js storefront with <strong>Razorpay</strong>, a <strong>video gallery</strong> mirroring her YouTube grid, and an <strong>admin panel</strong> where she adds products the way she'd add a video — title, thumbnail, done. Zero Shopify themes, zero builder lock-in, full code ownership.` },
    ],
    galleryLabel: "Gallery · 2 surfaces",
    gallery: [
      { src: "/images/work/chinkiz-1.webp", alt: "ChinkiZ Knitting Knife — storefront hero" },
      { src: "/images/work/chinkiz-2.webp", alt: "ChinkiZ Knitting Knife — product collection grid" },
    ],
    faq: [
      { q: "What is ChinkiZ Knitting Knife?", a: "ChinkiZ Knitting Knife is a direct-to-consumer storefront built by Divyansh Sood Studio for Chinki, a creator with a 600K+ subscriber YouTube channel. The site puts her tutorial videos next to the buy button." },
      { q: "Does the store use Shopify or a website builder?", a: "No. It is fully custom-coded in Next.js with Razorpay payments — zero Shopify themes and zero builder lock-in, so the owner keeps full code ownership." },
      { q: "How does the owner add products?", a: "A custom admin panel lets her add a product the way she'd add a video — title, thumbnail, done — with a video gallery that mirrors her YouTube grid." },
    ],
    next: { slug: "nandini", name: "Nandini Travels", label: "Next · 04" },
  },
  {
    slug: "modernkbs",
    num: "05", name: "Modern K.B.S.", category: "Web App · Admin", year: "2024",
    liveUrl: "https://modernkbs.com",
    domain: "modernkbs.com",
    headline: "Modern K.B.S.", headlineTail: "— school site + admin panel",
    role: "Solo · Site + Admin Panel",
    stackLine: "Next.js · Supabase · Admin dashboard",
    title: "Modern K.B.S. — school site + admin panel · Case study · Divyansh Sood",
    description: "A senior secondary school in Ladwara. Website + application portal shipped together with a live admin panel. Quoted at 6 months elsewhere — delivered in 7 days.",
    ogTitle: "Modern K.B.S. — school portal · Case study",
    ogDescription: "School site + admissions admin panel — 6 months elsewhere, 7 days here.",
    ogImage: "https://www.divyanshsood.com/images/work/modernkbs-1.webp",
    keywords: "school website India, admissions portal, school admin panel, Next.js Supabase, education website developer, fast website delivery, Divyansh Sood",
    lead: `A senior secondary school in Ladwara. Website + application portal shipped together, live admin panel threaded through every surface. Other agencies quoted 6 months; we delivered in <em>7 days</em>.`,
    waHref: "https://wa.me/919816091875?text=Hi%20Divyansh,%20I%20want%20a%20school%20website%20with%20admin%20panel.",
    feature: { src: "/images/work/modernkbs-1.webp", alt: "Modern K.B.S. — homepage hero on desktop" },
    metrics: [
      { v: "7 days", l: "vs. 6 months quoted" },
      { v: "Site + Admin", l: "Same sprint" },
      { v: "I–XII", l: "Admissions live" },
      { v: "0 SaaS", l: "Recurring fees" },
    ],
    outcome: "Public site + admissions admin panel delivered in 7 days, where other agencies quoted 6 months.",
    body: [
      { span2: true, tag: "The brief", title: "Admissions before the academic cycle", type: "prose",
        html: `The school had been quoted six months and a recurring SaaS fee for an admissions portal. They needed it before the next cycle — measured in <em>weeks</em>, not quarters. And the office staff (not developers) had to run it.` },
      { tag: "In their words", type: "quote",
        quote: `"Every other agency said 6 months. Delivered in 7 days."`,
        attribution: "— Admin, Modern K.B.S., Ladwara" },
      { tag: "Stack", type: "list", items: ["Next.js", "Supabase", "Custom admin", "Razorpay (fees)"] },
      { span2: true, tag: "What we shipped", title: "Public site + admin panel, one sprint", type: "prose",
        html: `Faculty pages, fee structure, an enquiry-to-admission pipeline, and a <strong>dashboard the office uses daily</strong>. Zero learning curve — designed so any office staffer can update content without calling a developer.` },
    ],
    galleryLabel: "Gallery · 2 surfaces",
    gallery: [
      { src: "/images/work/modernkbs-1.webp", alt: "Modern K.B.S. — homepage hero" },
      { src: "/images/work/modernkbs-2.webp", alt: "Modern K.B.S. — notices and toppers" },
    ],
    faq: [
      { q: "What is Modern K.B.S.?", a: "Modern K.B.S. is a senior secondary school in Ladwara. Divyansh Sood Studio built its public website plus an admissions application portal and a live admin panel, all in one sprint." },
      { q: "How long did the build take?", a: "Seven days — where other agencies had quoted six months and a recurring SaaS fee." },
      { q: "Who runs the admin panel?", a: "Office staff, not developers. The dashboard was designed with zero learning curve so any staffer can update content and process admissions without calling a developer." },
    ],
    next: { slug: "webseek", name: "WebSeek.ai", label: "Next · 06" },
  },
  {
    slug: "nandini",
    num: "04", name: "Nandini Travels", category: "Travel · Local", year: "2025",
    liveUrl: "https://www.nandinitravel.com/",
    domain: "nandinitravel.com",
    headline: "Nandini Travels", headlineTail: "— Kangra taxi operator",
    role: "Solo · Design + Build",
    stackLine: "Next.js · WhatsApp · Booking form",
    title: "Nandini Travels — Kangra taxi operator · Case study · Divyansh Sood",
    description: "Kangra's most-reviewed taxi operator had a broken site and zero direct bookings — all leads via Google Maps. Rebuilt in Next.js with on-site booking + WhatsApp.",
    ogTitle: "Nandini Travels — Kangra taxi operator · Case study",
    ogDescription: "Next.js rebuild for Kangra's most-reviewed taxi operator. Direct bookings now flow through the site instead of Google Maps.",
    ogImage: "https://www.divyanshsood.com/images/work/nandini-1.webp",
    keywords: "Kangra taxi website, taxi operator website India, travel booking form, WhatsApp booking, Next.js travel site, direct bookings, Google Maps alternative, Divyansh Sood",
    lead: `Kangra's most-positively-reviewed taxi operator was losing every lead to Google Maps. Their old site was down. We rebuilt it in Next.js with an on-site booking form, WhatsApp CTA, outstation packages and an airport-pickup option. Direct bookings now flow through the site.`,
    waHref: "https://wa.me/919816091875?text=Hi%20Divyansh,%20I%20want%20a%20travel%20%2F%20taxi%20website.",
    feature: { src: "/images/work/nandini-1.webp", alt: "Nandini Travels — Kangra taxi operator homepage hero" },
    metrics: [
      { v: "10×", l: '"More premium" — founder' },
      { v: "Direct", l: "Bookings (vs. only Maps)" },
      { v: "Next.js", l: "Full rebuild" },
      { v: "N. India", l: "Outstation coverage" },
    ],
    outcome: "Direct bookings now flow through a site the operator owns, instead of leaking to Google Maps.",
    body: [
      { span2: true, tag: "The brief", title: "Best reviews in Kangra. Worst funnel.", type: "prose",
        html: `Nandini Travels has the strongest review profile of any taxi operator in Kangra — but every booking arrived through Google Maps, and the old website was down. There was no funnel they owned. Margins shrank with every Maps-driven enquiry.` },
      { tag: "In their words", type: "quote",
        quote: `"The website is so beautiful — looks 10 times more premium than our competitors. We started getting direct bookings instead of losing them to Google Maps."`,
        attribution: "— Founder, Nandini Travels" },
      { tag: "Stack", type: "list", items: ["Next.js", "WhatsApp deep-link", "Booking form", "Vercel"] },
      { span2: true, tag: "What we shipped", title: "A funnel they own — built around the WhatsApp moment", type: "prose",
        html: `A Next.js rebuild with an <strong>on-site booking form</strong>, a one-tap WhatsApp CTA on every package, outstation routes across North Indian states, and an airport-pickup flow. Faster than the old site. Mobile-first because almost every booking starts on a phone.` },
    ],
    galleryLabel: "Gallery · 2 surfaces",
    gallery: [
      { src: "/images/work/nandini-1.webp", alt: "Nandini Travels — homepage hero" },
      { src: "/images/work/nandini-2.webp", alt: "Nandini Travels — authorised-operator credentials" },
    ],
    faq: [
      { q: "What is Nandini Travels?", a: "Nandini Travels is Kangra's most-positively-reviewed taxi operator. Divyansh Sood Studio rebuilt their website in Next.js with an on-site booking form, a WhatsApp CTA, outstation packages and airport pickup." },
      { q: "Why did the site need rebuilding?", a: "Every booking used to arrive through Google Maps and the old site was down, so the operator owned no funnel. After the rebuild, direct bookings now flow through the site." },
      { q: "What did the founder say about the result?", a: "“The website is so beautiful — looks 10 times more premium than our competitors. We started getting direct bookings instead of losing them to Google Maps.”" },
    ],
    next: { slug: "modernkbs", name: "Modern K.B.S.", label: "Next · 05" },
  },
  {
    slug: "northpeak",
    // Personal project — shown on /portfolio under "Personal projects", kept off the homepage deck.
    personal: true,
    num: "08", name: "North Peak Power Systems", category: "Infra · Dashboard", year: "2025",
    liveUrl: "https://northpeakpowersystems.vercel.app/",
    domain: "northpeakpowersystems.vercel.app",
    headline: "North Peak Power Systems", headlineTail: "— solar contractor portal",
    role: "Solo · Site + Dashboard",
    stackLine: "Angular · Project gallery · Admin",
    title: "North Peak Power Systems — solar contractor portal · Divyansh Sood",
    description: "Himachal electrical & solar contractor breaking into the private sector. 15-page Angular site with project gallery, work calendar and self-serve admin.",
    ogTitle: "North Peak Power Systems — solar contractor portal · Case study",
    ogDescription: "15-page Angular site + dashboard-cum-admin for a Himachal electrical/solar contractor breaking into the private sector.",
    ogImage: "https://www.divyanshsood.com/images/work/northpeak-1.webp",
    keywords: "solar contractor website, electrical contractor portal, Angular website, project gallery, admin dashboard, Himachal solar, government to private, Divyansh Sood",
    lead: `Himachal electrical &amp; solar contractor doing mostly government work, breaking into the private sector dominated by digital + offline competitors. We shipped a 15-page Angular site, a project gallery, a work calendar and a dashboard-cum-admin — they publish new project case studies themselves.`,
    waHref: "https://wa.me/919816091875?text=Hi%20Divyansh,%20I%20want%20a%20site%20%2B%20admin%20panel%20for%20my%20business.",
    feature: { src: "/images/work/northpeak-1.webp", alt: "North Peak Power Systems — homepage hero on desktop" },
    metrics: [
      { v: "15", l: "Pages shipped" },
      { v: "Admin", l: "Self-publish projects" },
      { v: "Govt → Pvt", l: "Pivot live" },
      { v: "Angular", l: "Framework" },
    ],
    outcome: "A 15-page portal + self-serve admin that finally lets the team lead with a private-sector pitch.",
    body: [
      { span2: true, tag: "The brief", title: "Govt → private. With proof, not promises.", type: "prose",
        html: `The team was excellent at government tenders but invisible in the private market — where buyers want photos, recent projects and a clear pitch. The site had to <em>showcase work</em> credibly and let the team add new case studies themselves, not via a developer.` },
      { tag: "In their words", type: "quote",
        quote: `"Divyansh, exactly yahi chahiye tha. Humne pehle jisse karwaya tha vo sirf photos laga ke chala gaya. Mein apne circle mein lifetime zaroor refer karunga."`,
        attribution: "— Founder, North Peak Power Systems" },
      { tag: "Stack", type: "list", items: ["Angular", "Project gallery", "Work calendar", "Custom admin"] },
      { span2: true, tag: "What we shipped", title: "15 pages + a dashboard the team actually uses", type: "prose",
        html: `Service pages for solar, electrical and infra. A <strong>project gallery</strong> they update without dev help. A work calendar so prospects can see active engagements. A <strong>dashboard-cum-admin</strong> for new uploads — designed for a non-technical operator. Result: a private-sector pitch they can finally lead with.` },
    ],
    galleryLabel: "Gallery · 2 surfaces",
    gallery: [
      { src: "/images/work/northpeak-1.webp", alt: "North Peak Power Systems — homepage hero" },
      { src: "/images/work/northpeak-2.webp", alt: "North Peak Power Systems — services overview" },
    ],
    faq: [
      { q: "What is North Peak Power Systems?", a: "North Peak Power Systems is a Himachal electrical and solar contractor. Divyansh Sood Studio built a 15-page Angular site with a project gallery, work calendar and a dashboard-cum-admin to help them break into the private sector." },
      { q: "Can the team publish new projects without a developer?", a: "Yes — a dashboard-cum-admin, designed for a non-technical operator, lets the team upload new project case studies and update the gallery themselves." },
      { q: "What framework was used?", a: "Angular, across all 15 pages, with a custom admin dashboard." },
    ],
    next: { slug: "dharamshala-tours", name: "Dharamshala Tours", label: "Next · 09" },
  },
  {
    slug: "cultxberserk",
    num: "02", name: "CultXberserk", category: "Brand · D2C", year: "2026",
    liveUrl: "https://cultxberserk.com",
    domain: "cultxberserk.com",
    headline: "CultXberserk", headlineTail: "— Berserk-inspired apparel",
    role: "Solo · Brand + Build",
    stackLine: "Next.js · ImageKit · Custom storefront",
    title: "CultXberserk — Berserk-inspired apparel brand · Divyansh Sood",
    description: "A gothic apparel label built around the world of Berserk. Hand-numbered drops (0001–0666), 13 designs never reprinted. Custom-coded — no Shopify theme.",
    ogTitle: "CultXberserk — Berserk-inspired apparel · Case study",
    ogDescription: "A lore-driven apparel brand with hand-numbered drops and a custom-coded storefront. No Shopify theme.",
    ogImage: "https://www.divyanshsood.com/images/work/cultxberserk-1.webp",
    keywords: "Berserk apparel, gothic streetwear brand, hand-numbered drops, custom e-commerce India, Next.js storefront, anime apparel, D2C clothing brand, no Shopify, Divyansh Sood",
    lead: `A gothic apparel label built around the world of Berserk. Heavyweight, garment-dyed tees that are hand-numbered (0001–0666) and never reprinted — each carrying a "Brand of Sacrifice" seal at the neckline. The storefront is custom-coded, so the lore and the buy flow are one experience.`,
    waHref: "https://wa.me/919816091875?text=Hi%20Divyansh,%20I%20want%20a%20brand%20storefront.",
    feature: { src: "/images/work/cultxberserk-1.webp", alt: "CultXberserk — lore-driven storefront hero on desktop" },
    metrics: [
      { v: "0001–0666", l: "Hand-numbered units" },
      { v: "13", l: "Designs, never reprinted" },
      { v: "240gsm", l: "Garment-dyed cotton" },
      { v: "0", l: "Shopify themes" },
    ],
    outcome: "A custom-coded storefront where the lore, the drop mechanics and the buy flow are one experience — not a dressed-up theme.",
    body: [
      { span2: true, tag: "The bet", title: "Lore-driven commerce, not a merch store", type: "prose",
        html: `Most anime-adjacent labels print a graphic and ship it on a generic store. CultXberserk is the opposite: a brand with its own canon — Japanese lettering, Roman numerals, a <em>"Brand of Sacrifice"</em> seal at the C7 vertebra — where the storytelling and the storefront are built as one thing.` },
      { tag: "Brand voice", type: "quote",
        quote: `"Apparel for the damned."` },
      { tag: "Stack", type: "list", items: ["Next.js", "ImageKit", "Custom cart", "Drop mechanics"] },
      { span2: true, tag: "What we shipped", title: "A storefront that reads like the manga", type: "prose",
        html: `A custom Next.js storefront with <strong>ImageKit</strong>-optimised product imagery, a <strong>hand-numbered drop system</strong> (0001–0666, never reprinted), and dedicated <em>Lore</em>, <em>Drops</em> and <em>Council</em> surfaces so the world-building lives next to the buy button. Zero Shopify themes — full code ownership, end to end.` },
    ],
    galleryLabel: "Gallery · 2 surfaces",
    gallery: [
      { src: "/images/work/cultxberserk-1.webp", alt: "CultXberserk — lore-driven storefront hero" },
      { src: "/images/work/cultxberserk-2.webp", alt: "CultXberserk — brand lore section" },
    ],
    faq: [
      { q: "What is CultXberserk?", a: "CultXberserk is a gothic apparel brand inspired by Kentaro Miura's manga Berserk, with a custom-coded storefront built by Divyansh Sood Studio. It sells heavyweight, garment-dyed tees that are hand-numbered and never reprinted." },
      { q: "Was the store built on Shopify?", a: "No. It is a custom Next.js storefront with ImageKit-optimised imagery and a bespoke drop system — zero Shopify themes, so the brand keeps full code ownership." },
      { q: "What makes the drops exclusive?", a: "Every garment is hand-numbered from 0001 to 0666 across 13 designs and is never reprinted, and each carries a 'Brand of Sacrifice' seal sewn into the neckline at the C7 vertebra." },
    ],
    next: { slug: "chinkiz", name: "ChinkiZ Knitting Knife", label: "Next · 03" },
  },
];
